<script>
    window._ugsNameMap = {
"1": "1",
"100RoomsOfEnemies": "100 Rooms of Enemies",
"10bullets": "10 Bullets",
"10minutestildawn": "10 Minutes Till Dawn",
"10morebullets": "10 More Bullets",
"12minibattles": "12 Mini Battles",
"13bones": "13 Bones",
"1on1soccer": "1 on 1 Soccer",
"1v1lol": "1v1.LOL",
"1v1tennis": "1v1 Tennis",
"2048": "2048",
"2048cupcakes": "2048 Cupcakes",
"20smallmazes": "20 Small Mazes",
"234playergame": "2-3-4 Player Game",
"2doom": "2 Doom",
"2Dshooting": "2D Shooting",
"3dash": "3 Dash",
"3dasheditor": "3 Dash Editor",
"3dpinballspacecadet": "3D Pinball Space Cadet",
"3pandas": "3 Pandas",
"3pandasbrazil": "3 Pandas in Brazil",
"3pandasfantasy": "3 Pandas Fantasy",
"3pandasjapan": "3 Pandas in Japan",
"3pandasnight": "3 Pandas in Night",
"3slices2": "3 Slices 2",
"40xescape": "40x Escape",
"4thandgoal": "4th and Goal",
"500calibercontractz": "500 Caliber Contractz",
"60secondsburgerrun": "60 Seconds Burger Run",
"60secondssantarun": "60 Seconds Santa Run",
"64in1nes": "64 in 1 NES",
"8ballclassic": "8 Ball Classic",
"8ballpool": "8 Ball Pool",
"9007199254740992": "9007199254740992",
"90in1nes": "90 in 1 NES",
"99balls": "99 Balls",
"99nightsitf": "99 Nights in the Forest",
"A Walk in The Forest (v10)": "A Walk in the Forest",
"abandoned3": "Abandoned 3",
"absolutemadness": "Absolute Madness",
"acecombat2": "Ace Combat 2",
"acecombat3": "Ace Combat 3",
"acegangstertaxi": "Ace Gangster Taxi",
"achievementunlocked": "Achievement Unlocked",
"achievmentunlocked": "Achievement Unlocked",
"achievmentunlocked2": "Achievement Unlocked 2",
"achievmentunlocked3": "Achievement Unlocked 3",
"achillies": "Achilles",
"achillies2": "Achilles 2",
"Acko_s Mach Bike Challenge (v10)": "Acko's Mach Bike Challenge",
"ADarkRoom": "A Dark Room",
"adatewithdeath": "A Date With Death",
"adayintheoffice": "A Day in the Office",
"ADOFAI": "A Dance of Fire and Ice",
"advancewars": "Advance Wars",
"advancewars2": "Advance Wars 2",
"advancewarsdualstrike": "Advance Wars Dual Strike",
"adventneon": "Advent Neon",
"AdventureCapatalist": "Adventure Capitalist",
"adventurecapitalist": "Adventure Capitalist",
"aflac": "Aflac",
"aftertheweek": "After the Week",
"agariolite": "Agario Lite",
"ageofwar": "Age of War",
"ageofwar2": "Age of War 2",
"agesofconflict": "Ages of Conflict",
"agesofempire": "Ages of Empire",
"ahoysurvival": "Ahoy Survival",
"ai": "AI",
"airlinetycoonidle": "Airline Tycoon Idle",
"akoopasrevenge": "A Koopa's Revenge",
"akoopasrevenge2": "A Koopa's Revenge 2",
"akumanorgaiden": "Akuma no R Gaiden",
"aladdinsnes": "Aladdin (SNES)",
"alexkiddinmiracleworld": "Alex Kidd in Miracle World",
"alienhominid": "Alien Hominid",
"alienhominidgba": "Alien Hominid (GBA)",
"alienskyinvasion": "Alien Sky Invasion",
"alientransporter": "Alien Transporter",
"alienvspredator": "Alien vs. Predator",
"allbossesin1": "All Bosses in 1",
"allocation": "Allocation",
"Altered Beast": "Altered Beast",
"amaze": "Amaze",
"ambulencearush": "Ambulance Rush",
"amidstthesky": "Amidst the Sky",
"amigopancho": "Amigo Pancho",
"amigopancho2": "Amigo Pancho 2",
"amigopancho3": "Amigo Pancho 3",
"amigopancho4": "Amigo Pancho 4",
"amigopancho5": "Amigo Pancho 5",
"amigopancho6": "Amigo Pancho 6",
"amigopancho7": "Amigo Pancho 7",
"amongus": "Among Us",
"amorphous": "Amorphous+",
"ancientsins": "Ancient Sins",
"anemonesfall": "Anemones Fall",
"angry-birdsspace": "Angry Birds Space",
"angrybirds-space": "Angry Birds Space",
"angrybirds": "Angry Birds",
"angrybirdsshowdown": "Angry Birds Showdown",
"angrybirdsspace": "Angry Birds Space",
"animalcrossingwildworld": "Animal Crossing: Wild World",
"animalforestn64": "Animal Forest (N64)",
"annsmb": "Another Super Mario Bros",
"anotherworld": "Another World",
"antarttycoon": "Antarctic Tycoon",
"antimatterdimensions": "Antimatter Dimensions",
"apesvshelium": "Apes vs. Helium",
"apotris": "Apotris",
"appleshooter": "Apple Shooter",
"appleworm": "Apple Worm",
"aquaparkio": "Aquapark.io",
"arceuslegend": "Arceus Legend",
"archeryworldtour": "Archery World Tour",
"archesspelago": "Arch Espelago",
"arena": "Arena",
"armormayhem2": "Armor Mayhem 2",
"arsonate": "Arsonate",
"arthursnightmare": "Arthur's Nightmare",
"ascent": "Ascent",
"asdutydemands": "As Duty Demands",
"asmallworldcup": "A Small World Cup",
"assesmentexaminationque": "Assessment Examination",
"assesmentexamination": "Assessment Examination",
"asteroids": "Asteroids",
"asteroidsALT": "Asteroids (Alt)",
"asteroidsarcade": "Asteroids Arcade",
"AstrosDreamland": "Astro's Dreamland",
"astynax": "Astyanax",
"atariadventure": "Atari Adventure",
"attackhole": "Attack Hole",
"avalanche": "Avalanche",
"aviamasters": "Avia Masters",
"aviamastersbuggy": "Avia Masters Buggy",
"AwesomePirates": "Awesome Pirates",
"awesomeplanes": "Awesome Planes",
"awesometanks": "Awesome Tanks",
"awesometanks2": "Awesome Tanks 2",
"axbattler": "Ax Battler",
"axisfootballleague": "Axis Football League",
"B3313": "B3313",
"b3313unabandonedA2": "B3313 Unabandoned A2",
"b3313v102": "B3313 v1.02",
"babeltower": "Babel Tower",
"babychiccoadventure": "Baby Chicco Adventure",
"babykaizo": "Baby Kaizo",
"babysniperinvietnam": "Baby Sniper in Vietnam",
"backrooms": "The Backrooms",
"backrooms2D": "The Backrooms 2D",
"backyardbaseball": "Backyard Baseball",
"backyardbaseball09": "Backyard Baseball '09",
"backyardbaseball10": "Backyard Baseball '10",
"backyardfootball": "Backyard Football",
"backyardsoccer": "Backyard Soccer",
"baconmaydie": "Bacon May Die",
"badbodyguards": "Bad Bodyguards",
"badicecream": "Bad Ice Cream",
"badicecream2": "Bad Ice Cream 2",
"badicecream3": "Bad Ice Cream 3",
"badmondaysimulator": "Bad Monday Simulator",
"badparenting": "Bad Parenting",
"badpiggies": "Bad Piggies",
"badpiggieslatest": "Bad Piggies (Latest)",
"badtimesim": "Bad Time Simulator",
"badtimesimulator": "Bad Time Simulator",
"balatrogba": "Balatro (GBA)",
"baldicaseoh": "Baldi's Case Oh",
"baldidecomp": "Baldi Decomp",
"baldiepstein": "Baldi Epstein",
"baldisbasics": "Baldi's Basics",
"baldisbasicsremaster": "Baldi's Basics Remaster",
"baldisfunnewschoolultimate": "Baldi's Fun New School Ultimate",
"ballblast": "Ball Blast",
"ballistic": "Ballistic",
"ballsandbricks": "Balls and Bricks",
"ballsandbricksgood": "Balls and Bricks (Good)",
"ballz": "Ballz",
"bananasimulator": "Banana Simulator",
"banbuds": "Banbuds",
"banditgunslingers": "Bandit Gunslingers",
"banjokazooie": "Banjo-Kazooie",
"banjotooie": "Banjo-Tooie",
"Bank Robbery": "Bank Robbery",
"bankbreakout2": "Bank Breakout 2",
"bankrobbery2": "Bank Robbery 2",
"barryhasasecret": "Barry Has a Secret",
"bartblast": "Bart Blast",
"bas": "BAS",
"baseballbros": "Baseball Bros",
"basketballfrvr": "Basketball FRVR",
"basketballlegends(1)": "Basketball Legends",
"basketballlegends": "Basketball Legends",
"basketballstars": "Basketball Stars",
"basketballsuperstars": "Basketball Superstars",
"basketbattle": "Basket Battle",
"basketbros": "Basket Bros",
"basketrandom": "Basket Random",
"basketrandomgood": "Basket Random (Good)",
"basketslamdunk2": "Basket Slam Dunk 2",
"batterup": "Batter Up",
"battlekarts": "Battle Karts",
"battles": "Battles",
"battlesim": "Battle Simulator",
"battlezone": "Battlezone",
"bazookaboy": "Bazooka Boy",
"bballlegend": "Basketball Legend",
"beachboxingsim": "Beach Boxing Simulator",
"beamrider": "Beamrider",
"bearbarians": "Bearbarians",
"bearsus": "Bearsus",
"bejeweledtwistds": "Bejeweled Twist (DS)",
"bejeweledtwistflash": "Bejeweled Twist (Flash)",
"ben10alienforce": "Ben 10: Alien Force",
"ben10omniverse": "Ben 10: Omniverse",
"ben10protector": "Ben 10: Protector",
"ben10racing": "Ben 10 Racing",
"ben10ultimatealien": "Ben 10: Ultimate Alien",
"bendrowned": "Ben Drowned",
"bergentruck201x": "Bergen Truck 201X",
"bfdia5b": "BFDIA 5b",
"BFDIBranches": "BFDI Branches",
"bigflappytowertinysquare": "Big Flappy Tower Tiny Square",
"bigicetowertinysquare": "Big Ice Tower Tiny Square",
"bigneontowertinysquare": "Big Neon Tower Tiny Square",
"bigshotboxing2": "Big Shot Boxing 2",
"bigtowertinysquare": "Big Tower Tiny Square",
"bigtowertinysquare2": "Big Tower Tiny Square 2",
"bigtowertinysquare2good": "Big Tower Tiny Square 2 (Good)",
"Big_Time_Butter_Baron": "Big Time Butter Baron",
"bindingofisaccsheeptime": "Binding of Isaac: Sheep Time",
"bioevil4": "Bio Evil 4",
"bitlife": "BitLife",
"bitlifeencrypted": "BitLife (Encrypted)",
"bitplanes": "Bit Planes",
"blackjack": "Blackjack",
"blackjackbattle": "Blackjack Battle",
"blackjackhhhh": "Blackjack",
"blackknight": "Black Knight",
"blackout": "Blackout",
"blacksmithlab": "Blacksmith Lab",
"blastronaut": "Blastronaut",
"blazedrifter": "Blaze Drifter",
"bleachvsnaruto": "Bleach vs. Naruto",
"blightborne": "Blightborne",
"blobsstory2": "Blob's Story 2",
"blockblast": "Block Blast",
"blockblastv2": "Block Blast v2",
"blockcraftparkour": "Block Craft Parkour",
"blockcraftshooter": "Block Craft Shooter",
"blockpost": "Blockpost",
"blockthepig": "Block the Pig",
"blockydemolitionderby": "Blocky Demolition Derby",
"blockysnakes": "Blocky Snakes",
"blood": "Blood",
"bloodmoney": "Blood Money",
"bloodtournament": "Blood Tournament",
"bloons": "Bloons",
"bloons2": "Bloons 2",
"bloonspp1": "Bloons Player Pack 1",
"bloonspp2": "Bloons Player Pack 2",
"bloonspp3": "Bloons Player Pack 3",
"bloonspp4": "Bloons Player Pack 4",
"bloonspp5": "Bloons Player Pack 5",
"bloonsTD1": "Bloons Tower Defense 1",
"bloonsTD2": "Bloons Tower Defense 2",
"bloonsTD3": "Bloons Tower Defense 3",
"bloonsTD4": "Bloons Tower Defense 4",
"bloonsTD5": "Bloons Tower Defense 5",
"bloonsTD6scratch": "Bloons Tower Defense 6 (Scratch)",
"bloxorz": "Bloxorz",
"blumgiracers": "Blumgi Racers",
"blumgirocket": "Blumgi Rocket",
"BMX2": "BMX 2",
"bntts": "BNTTS",
"bobasimulator": "Boba Simulator",
"bobtherobber": "Bob the Robber",
"bobtherobber2": "Bob the Robber 2",
"bobtherobber5": "Bob the Robber 5",
"bollybeat": "Bolly Beat",
"bomberman": "Bomberman",
"bomberman2": "Bomberman 2",
"bombermanhero": "Bomberman Hero",
"bombermanworld": "Bomberman World",
"Bonanza-Bros": "Bonanza Bros.",
"bonkerssnes": "Bonkers (SNES)",
"boomslingers": "Boomslingers",
"bottlecracks": "Bottle Cracks",
"bottleflip3d": "Bottle Flip 3D",
"botwds": "Breath of the Wild (DS)",
"bounceback": "Bounce Back",
"bouncemasters": "Bounce Masters",
"bouncybasketball": "Bouncy Basketball",
"bouncymotors": "Bouncy Motors",
"BountyOfOne": "Bounty of One",
"bowlalt": "Bowl (Alt)",
"bowmaster": "Bowmaster",
"boxhead2playrooms": "Boxhead 2Play Rooms",
"boxheadnightmare": "Boxhead Nightmare",
"boxinglive-2": "Boxing Live 2",
"boxinglive2": "Boxing Live 2",
"boxingrandom": "Boxing Random",
"brainrot": "Brainrot",
"brawlsimulator3d": "Brawl Simulator 3D",
"Brawlstars": "Brawl Stars",
"breadskate": "Bread Skate",
"bridgerace": "Bridge Race",
"brotato": "Brotato",
"BTD1": "Bloons Tower Defense 1",
"btd5": "Bloons Tower Defense 5",
"btts": "BTTS",
"btts2": "BTTS 2",
"bubbleshooter": "Bubble Shooter",
"bubbleshooterpirate": "Bubble Shooter Pirate",
"bubbletanks": "Bubble Tanks",
"bubbletanks2": "Bubble Tanks 2",
"bubbletanks3": "Bubble Tanks 3",
"bubbletanksarenas": "Bubble Tanks Arenas",
"bubbletankstd": "Bubble Tanks Tower Defense",
"bubsy": "Bubsy",
"buckshotroulette": "Buckshot Roulette",
"buildnowgg": "BuildNow GG",
"bulletforce": "Bullet Force",
"bunnyland": "Bunny Land",
"bunzobunny": "Bunzo Bunny",
"burgerandfrights": "Burger and Frights",
"burgertime": "Burger Time",
"burritobison": "Burrito Bison",
"burritobison2": "Burrito Bison 2",
"burritobisonlaunchalibre": "Burrito Bison: Launcha Libre",
"burritobisonrevenge": "Burrito Bison: Revenge",
"bushidoblade": "Bushido Blade",
"BusterJam": "Buster Jam",
"cactusmccoy(1)": "Cactus McCoy",
"cactusmccoy": "Cactus McCoy",
"cactusmccoy2(1)": "Cactus McCoy 2",
"cactusmccoy2(2)": "Cactus McCoy 2",
"cactusmccoy2": "Cactus McCoy 2",
"callofbattle": "Call of Battle",
"camilla": "Camilla",
"candybox1": "Candy Box",
"cannonballs3d": "Cannon Balls 3D",
"cannonfodder": "Cannon Fodder",
"captainlang": "Captain Lang",
"captchaware": "Captcha Ware",
"capybaraclicker": "Capybara Clicker",
"carcrash3": "Car Crash 3",
"cardrawing": "Car Drawing",
"careatscar2deluxe": "Car Eats Car 2 Deluxe",
"carkingarena": "Car King Arena",
"carmods": "Car Mods",
"carrampvspolicechase": "Car Ramp vs. Police Chase",
"carstuntsdriving": "Car Stunts Driving",
"CartoonNetworkTableTennisUltimateTournament": "Cartoon Network Table Tennis Ultimate Tournament",
"castaway": "Castaway",
"castlebloodline": "Castle Bloodline",
"castlecircleofmoon": "Castlevania: Circle of the Moon",
"castlevania": "Castlevania",
"castlevania2": "Castlevania II",
"castlevania3": "Castlevania III",
"castlevaniaariaofsorrow": "Castlevania: Aria of Sorrow",
"castlevaniadawnofsorrow": "Castlevania: Dawn of Sorrow",
"castlevanianes": "Castlevania (NES)",
"castlewarsmodern": "Castle Wars Modern",
"catmario": "Cat Mario",
"catmariogood": "Cat Mario (Good)",
"catslovecake2": "Cats Love Cake 2",
"cavecrawler": "Cave Crawler",
"cavestory": "Cave Story",
"celeste": "Celeste",
"celeste2": "Celeste 2",
"celestemariodx": "Celeste Mario DX",
"CeliasStupidROMHack": "Celia's Stupid ROM Hack",
"cellardoor": "Cellar Door",
"CellToSingularity": "Cell to Singularity",
"centipedearcade": "Centipede Arcade",
"chainofmemories": "Kingdom Hearts: Chain of Memories",
"chaosfaction2": "Chaos Faction 2",
"checkers": "Checkers",
"cheesechompers3d": "Cheese Chompers 3D",
"cheeseisthereason": "Cheese is the Reason",
"cheeserolling": "Cheese Rolling",
"cheshireinachatroom": "Cheshire in a Chat Room",
"chess": "Chess",
"chessclassic": "Chess Classic",
"chibiknight": "Chibi Knight",
"ChickenCS": "Chicken CS",
"chickenscream": "Chicken Scream",
"chickenwar": "Chicken War",
"chipschallenge": "Chip's Challenge",
"choppyorc": "Choppy Orc",
"choroqwonderful": "Choro Q Wonderful",
"chronotrigger": "Chrono Trigger",
"chuzzle": "Chuzzle",
"CircloO2": "CircloO 2",
"civiballs": "Civiballs",
"civiballs2": "Civiballs 2",
"clashnslash": "Clash N Slash",
"clashofvikings": "Clash of Vikings",
"classof09": "Class of '09",
"claymore": "Claymore",
"clayuncraft": "Clay Uncraft",
"cleanupio": "Cleanup.io",
"clearvision": "Clear Vision",
"clearvision2": "Clear Vision 2",
"clearvision3": "Clear Vision 3",
"clearvision4": "Clear Vision 4",
"clearvision5": "Clear Vision 5",
"climbforbrainrots": "Climb for Brainrots",
"clmadnessambulation": "Madness: Ambulation",
"clover": "Clover",
"clubbytheseal": "Clubby the Seal",
"clusterrush": "Cluster Rush",
"coalllcdemo": "Coal LCD Demo",
"cod4": "Call of Duty 4",
"codblackopp": "Call of Duty: Black Ops",
"coddefiance": "Call of Duty: Defiance",
"codenamegordon": "Codename Gordon",
"codeorg": "Code.org",
"codeorgbutoffline": "Code.org (Offline)",
"codercraft": "Coder Craft",
"codmodernwarfare": "Call of Duty: Modern Warfare",
"codworldatwar": "Call of Duty: World at War",
"coffeemaker": "Coffee Maker",
"coldpines": "Cold Pines",
"colorburst3d": "Color Burst 3D",
"colormatch": "Color Match",
"colorwatersort3d": "Color Water Sort 3D",
"combopool": "Combo Pool",
"commandandconquer": "Command & Conquer",
"commanderkeen4": "Commander Keen 4",
"commanderkeen5": "Commander Keen 5",
"commanderkeen6": "Commander Keen 6",
"confrontingurself": "Confronting Yourself",
"confrontingyourself": "Confronting Yourself",
"conkersbadfurday": "Conker's Bad Fur Day",
"contra": "Contra",
"contra3": "Contra III",
"cookie-clicker": "Cookie Clicker",
"cookieclicker": "Cookie Clicker",
"cookieclickercool": "Cookie Clicker (Cool)",
"cookieclickergood": "Cookie Clicker (Good)",
"cookieclickermodmenu": "Cookie Clicker Mod Menu",
"cookingmama": "Cooking Mama",
"cookingmama2": "Cooking Mama 2",
"cookingmama3": "Cooking Mama 3",
"coreball": "Core Ball",
"coryinthehouse": "Cory in the House",
"cotlk": "Crypt of the Lich King",
"countmastersstickmangames": "Count Masters: Stickman Games",
"coverorange": "Cover Orange",
"coverorange2": "Cover Orange 2",
"coverorangejourneygangsters": "Cover Orange Journey: Gangsters",
"coverorangejourneyknights": "Cover Orange Journey: Knights",
"coverorangejourneypirates": "Cover Orange Journey: Pirates",
"coverorangejourneyspace": "Cover Orange Journey: Space",
"coverorangeplayerspack": "Cover Orange Players Pack",
"coverorangeplayerspack2": "Cover Orange Players Pack 2",
"coverorangeplayerspack3(1)": "Cover Orange Players Pack 3",
"coverorangeplayerspack3": "Cover Orange Players Pack 3",
"crankit!": "Crank It!",
"crankit": "Crank It",
"crash2": "Crash Bandicoot 2",
"crash3": "Crash Bandicoot 3",
"crashbandicoot (1)": "Crash Bandicoot",
"crashbandicoot": "Crash Bandicoot",
"crashbandicoot2": "Crash Bandicoot 2",
"crashteamracing": "Crash Team Racing",
"crazycars": "Crazy Cars",
"crazycattle3d": "Crazy Cattle 3D",
"crazychicken3D": "Crazy Chicken 3D",
"crazyclimber": "Crazy Climber",
"crazyfrogracer": "Crazy Frog Racer",
"crazymotorcycle": "Crazy Motorcycle",
"crazypenguincatapult": "Crazy Penguin Catapult",
"crazyplanelanding": "Crazy Plane Landing",
"crazytaxigba": "Crazy Taxi (GBA)",
"creaturecardidle": "Creature Card Idle",
"creeperworld2": "Creeper World 2",
"creepyinternetstories": "Creepy Internet Stories",
"creepynightfunkin": "Creepy Night Funkin'",
"crimsonmadness": "Crimson Madness",
"crossyroad": "Crossy Road",
"crunchball3000": "Crunchball 3000",
"CrystalCastles": "Crystal Castles",
"cs16": "Counter-Strike 1.6",
"cs6": "Counter-Strike",
"csds": "Counter-Strike (DS)",
"csgoclicker": "CS:GO Clicker",
"ctgpnitro": "CTGP Nitro",
"curveball(1)": "Curve Ball",
"curveball": "Curve Ball",
"customersupport": "Customer Support",
"cuttherope": "Cut the Rope",
"cuttheropeholiday": "Cut the Rope: Holiday",
"cuttheropetimetravel": "Cut the Rope: Time Travel",
"cvooc": "Cvooc",
"cyberbungracing": "Cyber Bung Racing",
"cybersensation": "Cyber Sensation",
"dadgame": "Dad Game",
"dadish": "Dadish",
"dadnme": "Dad and Me",
"daggerfall": "Daggerfall",
"dandysworldclicker": "Dandy's World Clicker",
"danktomb": "Dank Tomb",
"dasharena": "Dash Arena",
"dashio": "Dash.io",
"Dashmetry": "Dashmetry",
"datewithiraq": "Date with Iraq",
"dborigins": "Dragon Ball Origins",
"dborigins2": "Dragon Ball Origins 2",
"dbsniper": "DB Sniper",
"dbzattacksaiyans": "DBZ: Attack of the Saiyans",
"dbzdevolution": "DBZ Devolution",
"dbzsuperwarriorssonic": "DBZ Super Warriors vs. Sonic",
"dbzwarriors2": "DBZ Warriors 2",
"ddlc64": "DDLC 64",
"deadair": "Dead Air",
"deadestate": "Dead Estate",
"deadfrontieroutbreak": "Dead Frontier: Outbreak",
"deadfrontieroutbreak2": "Dead Frontier: Outbreak 2",
"deadlydescent": "Deadly Descent",
"deadplate": "Dead Plate",
"deadseat": "Dead Seat",
"deadzed": "Dead Zed",
"deadzed2": "Dead Zed 2",
"deathchase": "Death Chase",
"deathrun": "Death Run",
"deblob2": "de Blob 2",
"decision": "Decision",
"decision2": "Decision 2",
"decision3": "Decision 3",
"decisionmedieval": "Decision: Medieval",
"deepersleep": "Deeper Sleep",
"deepestsword": "The Deepest Sword",
"deepsleep": "Deep Sleep",
"defenderarcade": "Defender Arcade",
"defendyourcastle": "Defend Your Castle",
"defendyournuts": "Defend Your Nuts",
"defendyournuts2": "Defend Your Nuts 2",
"deltarune": "Deltarune",
"deltatraveler": "Delta Traveler",
"dementium": "Dementium",
"demolitionderbycrashracing": "Demolition Derby Crash Racing",
"demonblade": "Demon Blade",
"demonbluff": "Demon Bluff",
"diablo": "Diablo",
"diamondhollow": "Diamond Hollow",
"diamondhollow2": "Diamond Hollow 2",
"diddykong-racing": "Diddy Kong Racing",
"dieintheducngeon": "Die in the Dungeon",
"dieinthedungeon": "Die in the Dungeon",
"digdeep": "Dig Deep",
"digdug": "Dig Dug",
"digdug2": "Dig Dug 2",
"digdug26": "Dig Dug 26",
"digtochina": "Dig to China",
"dimensionalincident": "Dimensional Incident",
"dinodudes": "Dino Dudes",
"dinorun": "Dino Run",
"dinorunenterplanetd": "Dino Run: Enter Planet D",
"dinorunmarathonofdoom": "Dino Run: Marathon of Doom",
"diredecks": "Dire Decks",
"dkccompetitioncart": "DKC Competition Cart",
"DKNESCollection(1)": "Donkey Kong NES Collection",
"DKNESCollection": "Donkey Kong NES Collection",
"doblox": "Doblox",
"dogeminer": "Doge Miner",
"dogeminer2": "Doge Miner 2",
"dokidokiliteratureclub": "Doki Doki Literature Club",
"domeromantik": "Dome Romantik",
"donkeykong": "Donkey Kong",
"donkeykong64": "Donkey Kong 64",
"donkeykong94": "Donkey Kong '94",
"donkeykongcountry": "Donkey Kong Country",
"donkeykongcountry2": "Donkey Kong Country 2",
"donkeykongcountry3": "Donkey Kong Country 3",
"donkeykongnes": "Donkey Kong (NES)",
"dontescape": "Don't Escape",
"dontescape2": "Don't Escape 2",
"dontescape3": "Don't Escape 3",
"dontyoulecturemehtml": "Don't You Lecture Me",
"doodlejump": "Doodle Jump",
"doodlejumpgoober": "Doodle Jump Goober",
"doom": "Doom",
"doom2": "Doom II",
"doom2d": "Doom 2D",
"doom2dDOS": "Doom 2D (DOS)",
"doom2dos": "Doom 2 DOS",
"doom3pack": "Doom 3 Pack",
"doom64": "Doom 64",
"doomdos": "Doom (DOS)",
"doomemscripten": "Doom (Emscripten)",
"doomps": "Doom (PS1)",
"doompsalt": "Doom (PS1 Alt)",
"doomzio": "Doomz.io",
"doorscastle": "Doors: Castle",
"doswasmx": "DOSWasmX",
"doubledribble": "Double Dribble",
"douchebaglife": "Douchebag Life",
"douchebagworkout": "Douchebag Workout",
"douchebagworkout2": "Douchebag Workout 2",
"downthemountain": "Down the Mountain",
"dragonballadvance": "Dragon Ball Advance",
"DragonBallZTheLegacyofGoku": "Dragon Ball Z: The Legacy of Goku",
"dragonquest5ds": "Dragon Quest V (DS)",
"DragonQuestIX": "Dragon Quest IX",
"dragonwarriormonsters": "Dragon Warrior Monsters",
"Dragonxclient": "DragonX Client",
"drawclimber": "Draw Climber",
"drawntolife": "Drawn to Life",
"drawntolife2": "Drawn to Life 2",
"drawtheline": "Draw the Line",
"dreader": "D-Reader",
"dreadheadparkour": "Dread Head Parkour",
"driftboss": "Drift Boss",
"drifthuntersmerge": "Drift Hunters Merge",
"driftsimulator": "Drift Simulator",
"drivemady": "Drive Mady",
"drivenwild": "Driven Wild",
"driverussia": "Driver Russia",
"drmario": "Dr. Mario",
"drweedgaster": "Dr. Weed Gaster",
"dta6": "DTA6",
"dubstep": "Dubstep",
"duckhunt": "Duck Hunt",
"ducklfe5": "Duck Life 5",
"ducklife": "Duck Life",
"ducklife2": "Duck Life 2",
"ducklife3": "Duck Life 3",
"ducklife4": "Duck Life 4",
"ducklifebattle": "Duck Life: Battle",
"ducklifespace": "Duck Life: Space",
"ducklingsio": "Ducklings.io",
"ducktales": "DuckTales",
"ducktales2": "DuckTales 2",
"dud": "Dud",
"dukenukem2": "Duke Nukem 2",
"dukenukem3d": "Duke Nukem 3D",
"dumbwaystodie": "Dumb Ways to Die",
"dumpling": "Dumpling",
"dunebuggy": "Dune Buggy",
"dungeondeck": "Dungeon Deck",
"dungeonraid": "Dungeon Raid",
"dungeonsanddegenerategamblers": "Dungeons and Degenerate Gamblers",
"dunkshot": "Dunk Shot",
"duskchild": "Dusk Child",
"dyingdreams": "Dying Dreams",
"dynamiteheaddy": "Dynamite Headdy",
"Eaglercraft-Alpha-126-Offline": "Eaglercraft Alpha 1.2.6",
"Eaglercraft-Beta-1.3-Offline": "Eaglercraft Beta 1.3",
"Eaglercraft-Beta-13-Offline": "Eaglercraft Beta 1.3",
"Eaglercraft-Indev-Offline (1)": "Eaglercraft Indev",
"Eaglercraft-Indev-Offline(1)": "Eaglercraft Indev",
"Eaglercraft-Indev-Offline(2)": "Eaglercraft Indev",
"Eaglercraft-Indev-Offline": "Eaglercraft Indev",
"eaglercraft152": "Eaglercraft 1.5.2",
"EaglercraftL_19_v0_7_0_Offline_Signed(1)": "Eaglercraft 1.9",
"EaglercraftL_19_v0_7_0_Offline_Signed": "Eaglercraft 1.9",
"eaglercraftnebula": "Eaglercraft Nebula",
"eagleride": "Eagle Ride",
"earntodie": "Earn to Die",
"earntodie2": "Earn to Die 2",
"earthbound": "EarthBound",
"earthbound3": "EarthBound (Alt)",
"earthboundsnes": "EarthBound (SNES)",
"earthtaken": "Earth Taken",
"earthtaken2": "Earth Taken 2",
"earthtaken3": "Earth Taken 3",
"earthwormgg": "Earthworm GG",
"earthwormjim (1)": "Earthworm Jim",
"earthwormjim": "Earthworm Jim",
"earthwormjim2 (1)": "Earthworm Jim 2",
"earthwormjim2": "Earthworm Jim 2",
"edelweiss": "Edelweiss",
"edyscarsimulator": "Edy's Car Simulator",
"effinghail": "Effing Hail",
"effingmachines": "Effing Machines",
"effingworms": "Effing Worms",
"effingzombies": "Effing Zombies",
"egg": "Egg",
"eggycar": "Eggy Car",
"elasticface": "Elastic Face",
"electricman2": "Electric Man 2",
"elevatoraction": "Elevator Action",
"elytraflight": "Elytra Flight",
"emujs": "Emu.js",
"enchain": "Enchain",
"endacopia": "Endacopia",
"endlesswar4": "Endless War 4",
"endlesswar5": "Endless War 5",
"endlesswar5wow": "Endless War 5 (WoW)",
"endlesswar7": "Endless War 7",
"enduro": "Enduro",
"epicbattlefantasy5": "Epic Battle Fantasy 5",
"escalatingduel": "Escalating Duel",
"escaperoad": "Escape Road",
"escaperoadcity2": "Escape Road City 2",
"escapeschoolduel": "Escape School Duel",
"et": "E.T.",
"etrianoddyssey": "Etrian Odyssey",
"eurovisionsim": "Eurovision Simulator",
"evilglitch": "Evil Glitch",
"evolution": "Evolution",
"excitebike64": "Excitebike 64",
"exitpath": "Exit Path",
"exoobservation": "Exo Observation",
"extremerun3d": "Extreme Run 3D",
"factoryballs": "Factory Balls",
"factoryballs2": "Factory Balls 2",
"factoryballs3": "Factory Balls 3",
"factoryballs4": "Factory Balls 4",
"fairytalevsonepiece": "Fairy Tale vs. One Piece",
"fallguys": "Fall Guys",
"fallout": "Fallout",
"famidash": "Famidash",
"famidash128": "Famidash 128",
"famidashAlbum128": "Famidash Album 128",
"famidashBSides128": "Famidash B-Sides 128",
"famidashCSides128": "Famidash C-Sides 128",
"famidashDSides128": "Famidash D-Sides 128",
"familyguycorrupted": "Family Guy Corrupted",
"fancypantsadventure": "Fancy Pants Adventure",
"fancypantsadventure2": "Fancy Pants Adventure 2",
"fancypantsadventure3": "Fancy Pants Adventure 3",
"fancysnowboarding": "Fancy Snowboarding",
"fantasyzone": "Fantasy Zone",
"fashionbattle": "Fashion Battle",
"fattygenius": "Fatty Genius",
"fearassessment": "Fear Assessment",
"fearstofathomhomealone": "Fears to Fathom: Home Alone",
"feedthevoid": "Feed the Void",
"feedus": "Feed Us",
"feedus2": "Feed Us 2",
"feedus3": "Feed Us 3",
"feedus4": "Feed Us 4",
"feedus5": "Feed Us 5",
"ff2ws": "Final Fantasy II (WS)",
"FF3": "Final Fantasy III",
"ff6": "Final Fantasy VI",
"ffaf": "Final Fantasy After",
"ffmysticquest": "Final Fantasy Mystic Quest",
"FFsonic1": "Final Fantasy Sonic X1",
"FFsonic2": "Final Fantasy Sonic X2",
"FFsonic3": "Final Fantasy Sonic X3",
"FFsonic4": "Final Fantasy Sonic X4",
"FFsonic5": "Final Fantasy Sonic X5",
"FFsonic61": "Final Fantasy Sonic X6 Part 1",
"FFsonic62": "Final Fantasy Sonic X6 Part 2",
"FIFA07": "FIFA 07",
"FIFA10": "FIFA 10",
"FIFA11": "FIFA 11",
"FIFA2000(1)": "FIFA 2000",
"FIFA2000(2)": "FIFA 2000",
"fifa2000": "FIFA 2000",
"FIFA99": "FIFA 99",
"FIFAinternationalsoccer": "FIFA International Soccer",
"FIFAroadtoworldcup98": "FIFA: Road to World Cup 98",
"FIFAsoccer06": "FIFA Soccer 06",
"FIFAsoccer95": "FIFA Soccer 95",
"FIFAsoccer96": "FIFA Soccer 96",
"FIFAsoccer97": "FIFA Soccer 97",
"FIFAstreet2": "FIFA Street 2",
"finalearth2": "Final Earth 2",
"finalfantasy": "Final Fantasy",
"finalfantasy2nes": "Final Fantasy II (NES)",
"finalfantasy3nes": "Final Fantasy III (NES)",
"finalfantasyII": "Final Fantasy II",
"finalfantasyIX": "Final Fantasy IX",
"finalfantasylegend2": "Final Fantasy Legend II",
"finalfantasytactics": "Final Fantasy Tactics",
"finalfantasyVI": "Final Fantasy VI",
"finalfantasyVII": "Final Fantasy VII",
"finalfantasyVIId2": "Final Fantasy VII Disc 2",
"finalfantasyVIId3": "Final Fantasy VII Disc 3",
"finalfantasyVIItheothertetrr": "Final Fantasy VII: The Other Tetris",
"finalninja": "Final Ninja",
"findthealien": "Find the Alien",
"fireblob": "Fire Blob",
"fireboyandwatergirl": "Fireboy and Watergirl",
"fireboyandwatergirl2": "Fireboy and Watergirl 2",
"fireboyandwatergirl3": "Fireboy and Watergirl 3",
"fireboyandwatergirl5": "Fireboy and Watergirl 5",
"fireboyandwatergirl6": "Fireboy and Watergirl 6",
"fireemblem": "Fire Emblem",
"fisheatgettingbig": "Fish Eat Getting Big",
"fisquarium": "Fisquarium",
"fivenightsatbaldisredone": "Five Nights at Baldi's Redone",
"fivenightsatepsteins": "Five Nights at Epstein's",
"fivenightsatshreks": "Five Nights at Shrek's",
"fivenightsatshrekshotel": "Five Nights at Shrek's Hotel",
"fivenightsatyoshis": "Five Nights at Yoshi's",
"flappybird": "Flappy Bird",
"flashsonic": "Flash Sonic",
"floodrunner": "Flood Runner",
"floodrunner2": "Flood Runner 2",
"floodrunner4": "Flood Runner 4",
"fluidism": "Fluidism",
"fnac1": "Five Nights at Candy's",
"fnac2": "Five Nights at Candy's 2",
"FNAF": "Five Nights at Freddy's",
"FNAF2": "Five Nights at Freddy's 2",
"FNAF3": "Five Nights at Freddy's 3",
"fnaf3remastered": "Five Nights at Freddy's 3 Remastered",
"FNAF4": "Five Nights at Freddy's 4",
"fnaf4halloween": "FNAF 4 Halloween",
"fnafanimatronics": "FNAF Animatronics",
"fnafps": "FNAF PS",
"fnafshooter": "FNAF Shooter",
"fnafsl": "Five Nights at Freddy's: Sister Location",
"fnafucn": "FNAF UCN",
"fnafworldd": "FNAF World",
"fnaw": "Five Nights at Wario's",
"fnfaethos": "FNF: Aethos",
"fnfagoti": "FNF: Agoti",
"fnfakage": "FNF: Akage",
"fnfanimation": "FNF: Animation",
"fnfannie": "FNF: Annie",
"fnfasdf": "FNF: ASDF",
"fnfbelowdepths": "FNF: Below Depths",
"fnfbfdi26": "FNF: BFDI 26",
"fnfbinarybreakdown": "FNF: Binary Breakdown",
"fnfblackbetrayal": "FNF: Black Betrayal",
"fnfbside": "FNF: B-Side",
"fnfcamelliarudeblaster": "FNF: Camellia Rude Blaster",
"fnfcandycarrier": "FNF: Candy Carrier",
"fnfchara": "FNF: Chara",
"fnfcitytales": "FNF: City Tales",
"fnfclassified": "FNF: Classified",
"fnfcorrosion": "FNF: Corrosion",
"fnfcory": "FNF: Cory",
"fnfcrunchin": "FNF: Crunchin",
"fnfdeciever": "FNF: Deceiver",
"fnfdesolation": "FNF: Desolation",
"fnfdocumictxtv3": "FNF: Documic v3",
"fnfdokitakeoverplus": "FNF: Doki Takeover Plus",
"fnfdropandroll": "FNF: Drop and Roll",
"fnfdsides": "FNF: D-Sides",
"fnfdustin": "FNF: Dustin",
"fnfdusttale": "FNF: Dusttale",
"fnffleetway": "FNF: Fleetway",
"fnfflippedout": "FNF: Flipped Out",
"fnffnaf1": "FNF vs. FNAF 1",
"fnffnaf2": "FNF vs. FNAF 2",
"fnffnaf3": "FNF vs. FNAF 3",
"fnffnatpt": "FNF: FNAT Part",
"fnfgamebreakerbundle": "FNF: Game Breaker Bundle",
"fnfgfmode": "FNF: GF Mode",
"fnfgodot": "FNF: Godot",
"fnfgoldenapple": "FNF: Golden Apple",
"fnfhank": "FNF: Hank",
"fnfheartbreakhavoc": "FNF: Heartbreak Havoc",
"fnfherobrine": "FNF: Herobrine",
"fnfhex": "FNF: Hex",
"fnfholiday": "FNF: Holiday",
"fnfhorkglorpgloop": "FNF: Hork Glorp Gloop",
"fnfhotline": "FNF: Hotline",
"fnfhypnoslullaby": "FNF: Hypno's Lullaby",
"fnfimposter3": "FNF: Imposter v3",
"fnfimposterv4": "FNF: Imposter v4",
"fnfindiecross": "FNF: Indie Cross",
"fnfinfernalbout": "FNF: Infernal Bout",
"fnfinfiniteirida": "FNF: Infinite Irida",
"fnfironlung": "FNF: Iron Lung",
"fnfjapcreepypasta": "FNF: Japanese Creepypasta",
"fnfmadnesspoop": "FNF: Madness",
"fnfmaginagematches": "FNF: Maginage Matches",
"fnfmariomadnessdside": "FNF: Mario Madness D-Side",
"fnfmarioport": "FNF: Mario Port",
"fnfmcmadness": "FNF: MC Madness",
"fnfmidfight": "FNF: Mid-Fight Masses",
"fnfmiku": "FNF vs. Miku",
"fnfmobmod": "FNF: Mob Mod",
"fnfneo": "FNF: Neo",
"fnfpiggyfield": "FNF: Piggy Field",
"fnfplutoshi": "FNF: Plutoshi",
"fnfpokepastaperdition": "FNF: Pokepasta Perdition",
"fnfporifera": "FNF: Porifera",
"fnfqt": "FNF: QT",
"fnfremnants": "FNF: Remnants",
"fnfretrospecter": "FNF: Retrospecter",
"fnfrevmixed": "FNF: Rev Mixed",
"fnfrewrite": "FNF: Rewrite",
"fnfrhythmicrev": "FNF: Rhythmic Revolution",
"fnfrottensmoothie": "FNF: Rotten Smoothie",
"fnfselfpaced": "FNF: Self Paced",
"fnfshaggy4keys": "FNF: Shaggy 4 Keys",
"fnfshaggyxmatt": "FNF: Shaggy x Matt",
"fnfshucks-v2": "FNF: Shucks v2",
"fnfshucksv2": "FNF: Shucks v2",
"fnfsky": "FNF: Sky",
"fnfsoft": "FNF: Soft",
"fnfsonicexe": "FNF vs. Sonic.exe",
"fnfsonicexe4": "FNF vs. Sonic.exe 4",
"fnfstarlightmayhem": "FNF: Starlight Mayhem",
"fnfstridentcrisis": "FNF: Strident Crisis",
"fnftailsgetstrolled": "FNF: Tails Gets Trolled",
"fnftooslowfran": "FNF: Too Slow Fran",
"fnftricky": "FNF: Tricky",
"fnfTWIDDLEFINGER": "FNF: Twiddle Finger",
"fnfundertale": "FNF vs. Undertale",
"fnfvoid": "FNF: Void",
"fnfvstabi": "FNF vs. Tabi",
"fnfwaltenfiles": "FNF: Walten Files",
"fnfwednesday-infedility": "FNF: Wednesday Infidelity",
"fnfwhitty": "FNF: Whitty",
"fnfzardy": "FNF: Zardy",
"focus": "Focus",
"folderdungeon": "Folder Dungeon",
"footballbros": "Football Bros",
"footballlegends": "Football Legends",
"forknsausage": "Fork N Sausage",
"fortzone": "Fort Zone",
"fpa4p1": "Fancy Pants Adventure 4 Part 1",
"fpa4p2": "Fancy Pants Adventure 4 Part 2",
"freegemas": "Free Gemas",
"freerider": "Free Rider",
"freerider2": "Free Rider 2",
"freerider3": "Free Rider 3",
"fridaynightfunkin": "Friday Night Funkin'",
"froggerarcade": "Frogger Arcade",
"fromrusttoash": "From Rust to Ash",
"fruitninja": "Fruit Ninja",
"funkinmix": "Funkin Mix",
"funnybattle": "Funny Battle",
"funnybattle2": "Funny Battle 2",
"funnymadracing": "Funny Mad Racing",
"funnyshooter2": "Funny Shooter 2",
"funnyshooter22": "Funny Shooter 2",
"fuschiax": "Fuschia X",
"fused240": "Fused 240",
"fzero": "F-Zero",
"fzerox": "F-Zero X",
"gachaverse": "Gacha Verse",
"Gain Ground": "Gain Ground",
"galaga": "Galaga",
"gameandwatchcollection": "Game & Watch Collection",
"gamewatchgallery3": "Game & Watch Gallery 3",
"gangstabean": "Gangsta Bean",
"gangstabean2": "Gangsta Bean 2",
"gangsterbros": "Gangster Bros",
"garcello": "Garcello",
"garfcaughtinact": "Garfield Caught in the Act",
"gdlite": "GD Lite",
"generalchaos": "General Chaos",
"genericfightermaybe": "Generic Fighter (Maybe)",
"geometrydashscratch": "Geometry Dash Scratch",
"geometryvibes": "Geometry Vibes",
"georgeandtheprinter": "George and the Printer",
"getawayshootout": "Getaway Shootout",
"getontop": "Get on Top",
"Gettothetopalthoughthereisnotop": "Get to the Top (Although There Is No Top)",
"getyoked": "Get Yoked",
"ggshinobi": "GG Shinobi",
"ggshinobi2": "GG Shinobi II",
"ghosttrick": "Ghost Trick",
"gimmietheairpod": "Gimmie the Airpod",
"gladdihoppers": "Gladdi Hoppers",
"glfighters": "GL Fighters",
"gloryhunters": "Glory Hunters",
"glover": "Glover",
"goalsouthafrica": "Goal: South Africa",
"gobble": "Gobble",
"goingballs": "Going Balls",
"golddiggerfrvr": "Gold Digger FRVR",
"goldenaxe": "Golden Axe",
"goldenaxe2": "Golden Axe II",
"goldenaxe3": "Golden Axe III",
"goldeneye007": "GoldenEye 007",
"goldensun": "Golden Sun",
"goldensunnds": "Golden Sun (NDS)",
"GoldenSunTheLostAge": "Golden Sun: The Lost Age",
"goldminer": "Gold Miner",
"golfbattle": "Golf Battle",
"golforbit": "Golf Orbit",
"golfsunday": "Golf Sunday",
"goodbigtowertinysquare": "Good Big Tower Tiny Square",
"goodbigtowertinysquare2": "Good Big Tower Tiny Square 2",
"goodboygalaxy": "Good Boy Galaxy",
"goodmonkeymart": "Good Monkey Mart",
"gooftroopsnes": "Goof Troop (SNES)",
"googlebaseball": "Google Baseball",
"googledino": "Google Dinosaur",
"gorescriptclassic": "Gorescript Classic",
"gorillatagg": "Gorilla Tag",
"gotobed": "Go to Bed",
"grandactionsimulator-ny": "Grand Action Simulator NY",
"granddad": "Grand Dad",
"grandescapeprison": "Grand Escape Prison",
"grandtheftautoadvance": "Grand Theft Auto Advance",
"granny": "Granny",
"granny2": "Granny 2",
"granny22": "Granny 2",
"granny3": "Granny 3",
"grannycreepy": "Granny Creepy",
"grannynightmare": "Granny Nightmare",
"grannyy": "Granny",
"granturismo": "Gran Turismo",
"granturismo2": "Gran Turismo 2",
"grassmowing": "Grass Mowing",
"gravity": "Gravity",
"gravitymod": "Gravity (Mod)",
"greenergrassawaits": "Greener Grass Awaits",
"grey-box-testing": "Grey Box Testing",
"grimacebirthday": "Grimace Birthday",
"grindcraft": "Grindcraft",
"grn": "GRN",
"growagarden": "Grow a Garden",
"growdenio": "Growden.io",
"growmi": "Growmi",
"growyourgarden": "Grow Your Garden",
"gta": "Grand Theft Auto",
"gta2": "Grand Theft Auto 2",
"gta22": "Grand Theft Auto 2",
"gta2alt": "Grand Theft Auto 2 (Alt)",
"gtaalt": "Grand Theft Auto (Alt)",
"gtaalty": "Grand Theft Auto (Alt)",
"gtachina": "GTA China",
"gtamods": "GTA Mods",
"guesstheiranswer": "Guess Their Answer",
"gun-spin": "Gun Spin",
"gunblood": "Gun Blood",
"guncho": "Guncho",
"gunfighterjessejames": "Gunfighter: Jesse James",
"gunknight": "Gun Knight",
"gunmayhem": "Gun Mayhem",
"gunmayhem2": "Gun Mayhem 2",
"gunmayhem2goof": "Gun Mayhem 2 (Goof)",
"gunmayhemredux": "Gun Mayhem Redux",
"gunnight": "Gun Night",
"gunsmoke": "Gunsmoke",
"gunstarheroes": "Gunstar Heroes",
"gymstack": "Gym Stack",
"gyromite": "Gyromite",
"hacx": "HacX",
"hajimeippo": "Hajime no Ippo",
"hajimenoippo": "Hajime no Ippo",
"halflife": "Half-Life",
"halocombatdevolved": "Halo: Combat Evolved",
"handshakes": "Handshakes",
"handsofwar (1)": "Hands of War",
"handsofwar(1)": "Hands of War",
"handsofwar(2)": "Hands of War",
"handsofwar": "Hands of War",
"handulum": "Handulum",
"hanger": "Hanger",
"hanger2": "Hanger 2",
"hangonsms": "Hang On (SMS)",
"happyroom": "Happy Room",
"happywheels": "Happy Wheels",
"hardwaretycoon": "Hardware Tycoon",
"harmonyofdissonance": "Castlevania: Harmony of Dissonance",
"Haroldsbadday": "Harold's Bad Day",
"harvestio": "Harvest.io",
"harvestmoon": "Harvest Moon",
"harvestmoon2": "Harvest Moon 2",
"harvestmoon64": "Harvest Moon 64",
"hauntedschool": "Haunted School",
"hauntthehouse": "Haunt the House",
"heartandsoul": "Heart and Soul",
"heartandsoul121": "Heart and Soul 1.2.1",
"hei$t": "Heist",
"Helios-Offline (1)": "Helios",
"Helios-Offline": "Helios",
"helixjump": "Helix Jump",
"hellron": "Hellron",
"helpnobrakes": "Help No Brakes",
"heretic": "Heretic",
"hero3flyingrobot": "Hero 3: Flying Robot",
"herobrinereborn": "Herobrine Reborn",
"hextris": "Hextris",
"HighSpeed": "High Speed",
"highstakes": "High Stakes",
"highwayracer2": "Highway Racer 2",
"highwaytraffic3d": "Highway Traffic 3D",
"hillclimbracinglite": "Hill Climb Racing Lite",
"HiNoHomo": "Hi No Homo",
"hipsterkickball": "Hipster Kickball",
"hit8ox": "Hit Box",
"hitsinglereal": "Hit Single Real",
"hitstunfly": "Hitstun Fly",
"hl2doom": "Half-Life 2 Doom",
"hobo": "Hobo",
"hobo2": "Hobo 2",
"hobo3": "Hobo 3",
"hobo4": "Hobo 4",
"hobo5": "Hobo 5",
"hobo6": "Hobo 6",
"hobo7": "Hobo 7",
"hobovszombies": "Hobo vs. Zombies",
"HoennsLastWish": "Hoenn's Last Wish",
"holebattle": "Hole Battle",
"holeio": "Hole.io",
"hollowknight": "Hollow Knight",
"homesheephome": "Home Sheep Home",
"horrormickeymouse": "Horror Mickey Mouse",
"hotdogbush": "Hot Dog Bush",
"hotwax": "Hot Wax",
"houseofhazards": "House of Hazards",
"hoverracerdrive": "Hover Racer Drive",
"huggywuggypixel": "Huggy Wuggy Pixel",
"humanexpenditureprogram": "Human Expenditure Program",
"hungryknight": "Hungry Knight",
"hungrylamu": "Hungry Lamu",
"hyppersandbox": "Hypper Sandbox",
"icantbelievegoogleflaggedmeforthenameofthefilelol": "I Can't Believe Google Flagged This",
"ice age baby": "Ice Age Baby",
"icedodo": "Ice Dodo",
"icefishing": "Ice Fishing",
"icypurplehead": "Icy Purple Head",
"idlebreakout": "Idle Breakout",
"idledice": "Idle Dice",
"idlefootballmanager": "Idle Football Manager",
"idleidlegamedev": "Idle Idle Gamedev",
"idleminertycoon": "Idle Miner Tycoon",
"idleminorzamnshes12": "Idle Minor",
"impossiblequiz (1)": "The Impossible Quiz",
"impossiblequiz": "The Impossible Quiz",
"impossiblequiz2": "The Impossible Quiz 2",
"inclementemerald": "Inclement Emerald",
"indiantrucksimiulator": "Indian Truck Simulator",
"infinitecraft": "Infinite Craft",
"inkgame": "Ink Game",
"Inkwell (v104)": "Inkwell",
"innkeeper": "Innkeeper",
"insidestory": "Inside Story",
"insomniary": "Insomniary",
"intellisphere": "Intellisphere",
"interactivebuddy": "Interactive Buddy",
"intoruins": "Into Ruins",
"intospace": "Into Space",
"intospace2": "Into Space 2",
"intospace3": "Into Space 3",
"intothedeepweb": "Into the Deep Web",
"intrusion": "Intrusion",
"iqball": "iQ Ball",
"ironsnout": "Iron Snout",
"ironsoldier": "Iron Soldier",
"irori": "Irori",
"itgetssolonelyhere": "It Gets So Lonely Here",
"iwbtg": "I Wanna Be the Guy",
"jacksmith": "Jacksmith",
"jacksmithencryptedorsmthn": "Jacksmith (Encrypted)",
"jailbreakobbbobob": "Jailbreak Obby",
"jamesbondjr": "James Bond Jr.",
"jazzjackrabbit": "Jazz Jackrabbit",
"jazzjackrabbit2": "Jazz Jackrabbit 2",
"jefflings": "Jefflings",
"jellydadhero": "Jelly Dad Hero",
"jellydrift": "Jelly Drift",
"jellymario": "Jelly Mario",
"jellytruck": "Jelly Truck",
"jellytruckgood": "Jelly Truck (Good)",
"jetforcegemini": "Jet Force Gemini",
"jetpackjoyride": "Jetpack Joyride",
"jetrush": "Jet Rush",
"jetskiracing": "Jet Ski Racing",
"jmocraft": "JMO Craft",
"johnnytrigger": "Johnny Trigger",
"johnnyupgrade": "Johnny Upgrade",
"jojobaps1": "JoJo's Bizarre Adventure (PS1)",
"journeyarcade": "Journey Arcade",
"journeydownhill": "Journey Downhill",
"joustarcade": "Joust Arcade",
"jsvecx": "JSVECX",
"jumbomario": "Jumbo Mario",
"JUMP": "JUMP",
"jumpingshell": "Jumping Shell",
"junglebooksnes": "The Jungle Book (SNES)",
"jungledeerhunting": "Jungle Deer Hunting",
"jurassicpark": "Jurassic Park",
"justfalllol": "Just Fall Lol",
"justhitthebutton": "Just Hit the Button",
"justoneboss": "Just One Boss",
"kaizomarioworld": "Kaizo Mario World",
"kalikan": "Kalikan",
"kanyezone": "Kanye Zone",
"kapi": "Kapi",
"karatebros": "Karate Bros",
"karlson": "Karlson",
"kartbros": "Kart Bros",
"KenGriffeyJrPresentsMajorLeagueBaseball": "Ken Griffey Jr. Presents Major League Baseball",
"keroseneclient": "Kerosene Client",
"killerinstinct": "Killer Instinct",
"killover": "Kill Over",
"killtheiceagebabyadventure": "Kill the Ice Age Baby Adventure",
"kimjonguntilepuzzle": "Kim Jong-un Tile Puzzle",
"kingdomheartsdays": "Kingdom Hearts: 358/2 Days",
"kingdomheartsrecoded": "Kingdom Hearts Re:Coded",
"kingdomheartsrecodedalt": "Kingdom Hearts Re:Coded (Alt)",
"kirby64": "Kirby 64",
"kirby64crystalshards": "Kirby 64: The Crystal Shards",
"kirbyandtheamzingmirror": "Kirby & the Amazing Mirror",
"kirbycanvascurse": "Kirby: Canvas Curse",
"kirbysadventure": "Kirby's Adventure",
"kirbysdreamland": "Kirby's Dream Land",
"kirbysdreamland3": "Kirby's Dream Land 3",
"kirbysoftandwet": "Kirby's Soft and Wet",
"kirbysqueaksquad": "Kirby: Squeak Squad",
"kirbysuperstar": "Kirby Super Star",
"kirbysuperstarultra": "Kirby Super Star Ultra",
"kirbytiltandtumble": "Kirby Tilt 'n' Tumble",
"kittencannon": "Kitten Cannon",
"klifur": "Klifur",
"knifehit": "Knife Hit",
"knightmaretower": "Knightmare Tower",
"knockknock": "Knock Knock",
"konkrio": "Konkr.io",
"koopasrevenge": "Koopa's Revenge",
"kourio": "Kour.io",
"ks2teams": "KS2 Teams",
"laceysflashgames": "Lacey's Flash Games",
"lastfirered": "Last Fire Red",
"lasthorizon": "Last Horizon",
"laststand": "The Last Stand",
"laststand2": "The Last Stand 2",
"leaderstrike": "Leader Strike",
"leapandavoid2": "Leap and Avoid 2",
"learntofly": "Learn to Fly",
"learntofly2": "Learn to Fly 2",
"learntofly3": "Learn to Fly 3",
"LearnToFly3Debug": "Learn to Fly 3 (Debug)",
"learntoflyidle": "Learn to Fly Idle",
"learntoflyidlehack": "Learn to Fly Idle (Hack)",
"LegacyOfGoku": "Dragon Ball Z: Legacy of Goku",
"legobatman": "LEGO Batman",
"legobatman2superheroes": "LEGO Batman 2: DC Super Heroes",
"legoindianajones": "LEGO Indiana Jones",
"legoindianajones2": "LEGO Indiana Jones 2",
"legoninjago": "LEGO Ninjago",
"legostarwars": "LEGO Star Wars",
"legostarwars2gba": "LEGO Star Wars 2 (GBA)",
"legostarwarsgba": "LEGO Star Wars (GBA)",
"lemmings": "Lemmings",
"letitconsume": "Let it Consume",
"letsgoeevee": "Let's Go Eevee",
"letsgopikachu": "Let's Go Pikachu",
"leveldevil": "Level Devil",
"leverwarriors": "Lever Warriors",
"lightitup": "Light It Up",
"lilrunmo": "Lil' Runmo",
"lime": "Lime",
"linerider": "Line Rider",
"linksawakeningdx": "Zelda: Link's Awakening DX",
"linktothepast": "Zelda: A Link to the Past",
"littlealchemy2": "Little Alchemy 2",
"littlerunmo": "Little Runmo",
"lockthedoor": "Lock the Door",
"loderunner": "Lode Runner",
"lonewolf": "Lone Wolf",
"losangelesshark": "Los Angeles Shark",
"lowknight": "Low Knight",
"loz1": "Legend of Zelda",
"lozlinkawakening": "Zelda: Link's Awakening",
"lozminishcap": "Zelda: The Minish Cap",
"lozoracleofseasons": "Zelda: Oracle of Seasons",
"lozphantomhourglass": "Zelda: Phantom Hourglass",
"lozspirittracks": "Zelda: Spirit Tracks",
"LSE": "LSE",
"lucid": "Lucid",
"luckyblocks": "Lucky Blocks",
"lumberobby": "Lumber Obby",
"lummm": "Lummm",
"madalinstuntcars": "Madalin Stunt Cars",
"madalinstuntcarsgood": "Madalin Stunt Cars (Good)",
"madalinstuntcarsmultiplayerfixed": "Madalin Stunt Cars Multiplayer",
"madden93": "Madden '93",
"madden94": "Madden '94",
"madden95": "Madden '95",
"madden96": "Madden '96",
"madden99": "Madden '99",
"maddenfootball": "Madden Football",
"maddenfootball64": "Madden Football 64",
"maddennfl": "Madden NFL",
"maddennfl2000": "Madden NFL 2000",
"maddennfl2001": "Madden NFL 2001",
"maddennfl2002": "Madden NFL 2002",
"maddy98": "Maddy '98",
"madness-retaliation": "Madness: Retaliation",
"madnessaccelerant": "Madness: Accelerant",
"madnesscombatdefense": "Madness Combat: Defense",
"madnesscombatnexus": "Madness Combat: Nexus",
"madnessgemini": "Madness: Gemini",
"madnesshydraulic": "Madness: Hydraulic",
"madnessinteractive": "Madness Interactive",
"madnessoffcolor": "Madness: Off Color",
"madnesspremediation": "Madness: Premediation",
"madnessretaliation": "Madness: Retaliation",
"madnesss2010": "Madness Combat 2010",
"madnessstand": "Madness: The Stand",
"madskillsmotocross2": "Mad Skills Motocross 2",
"madstick": "Mad Stick",
"madstuntcars2": "Mad Stunt Cars 2",
"magetoweridle": "Mage Tower Idle",
"magictiles3": "Magic Tiles 3",
"majorasmask": "Zelda: Majora's Mask",
"makesureitsclosed": "Make Sure It's Closed",
"mami": "Mami",
"managod": "Mana God",
"marbleracer(1)": "Marble Racer",
"marbleracer": "Marble Racer",
"mari0": "Mari0",
"Mario Party Advance": "Mario Party Advance",
"mario3": "Super Mario Bros. 3",
"mario64webgl": "Super Mario 64 (WebGL)",
"marioandluigisuperstarsaga": "Mario & Luigi: Superstar Saga",
"mariobuilder64(1)": "Mario Builder 64",
"mariobuilder64": "Mario Builder 64",
"mariocombat": "Mario Combat",
"mariogolf": "Mario Golf",
"MarioisMissingDoneRight": "Mario is Missing Done Right",
"mariokart64": "Mario Kart 64",
"mariokartds": "Mario Kart DS",
"mariokartsupercircuit": "Mario Kart: Super Circuit",
"mariolostlevels": "Super Mario Bros.: The Lost Levels",
"mariomadness": "Mario Madness",
"mariomakersnes": "Mario Maker (SNES)",
"mariominusrabbids": "Mario Minus Rabbids",
"mariopaint": "Mario Paint",
"marioparty": "Mario Party",
"marioparty2": "Mario Party 2",
"marioparty3": "Mario Party 3",
"mariopartyds": "Mario Party DS",
"mariosmysterymeat": "Mario's Mystery Meat",
"mariotennis": "Mario Tennis",
"mariotennisgb": "Mario Tennis (GB)",
"mariovsluigi": "Mario vs. Luigi",
"MarvelSuperHeroesArcade": "Marvel Super Heroes Arcade",
"MarvelVsCapcomPS1": "Marvel vs. Capcom (PS1)",
"MarvelVsStreetFighter": "Marvel vs. Street Fighter",
"marvelvsstreetfighterjp": "Marvel vs. Street Fighter (JP)",
"maskedforcesunlimited": "Masked Forces Unlimited",
"mastermindworldconquerer": "Mastermind: World Conqueror",
"matrixrampage": "Matrix Rampage",
"mattv2": "Matt v2",
"mauimallard": "Maui Mallard",
"maxpayne": "Max Payne",
"mcfpsfbhd": "Minecraft FPS BHD",
"mcraerally": "McRae Rally",
"meatboy": "Meat Boy",
"meatboyflash": "Meat Boy (Flash)",
"medalofhonor": "Medal of Honor",
"medievalshark": "Medieval Shark",
"medievil": "MediEvil",
"megacd": "Mega CD",
"megachess": "Mega Chess",
"megaclient": "Mega Client",
"megaman": "Mega Man",
"megaman2": "Mega Man 2",
"megaman2gba": "Mega Man 2 (GBA)",
"megaman3": "Mega Man 3",
"megaman4": "Mega Man 4",
"megaman5": "Mega Man 5",
"megaman5gb": "Mega Man 5 (GB)",
"megaman6": "Mega Man 6",
"megaman7": "Mega Man 7",
"megaman8": "Mega Man 8",
"megamanbasscftf": "Mega Man & Bass: Challenger from the Future",
"megamanbattlechipchallenge": "Mega Man Battle Chip Challenge",
"megamanbn5tc": "Mega Man Battle Network 5: Team Colonel",
"megamanbn5tp": "Mega Man Battle Network 5: Team Protoman",
"megamanbn6cf": "Mega Man Battle Network 6: Cybeast Falzar",
"megamanbn6cg": "Mega Man Battle Network 6: Cybeast Gregar",
"megamanlegends": "Mega Man Legends",
"megamanlegends2": "Mega Man Legends 2",
"megamanx": "Mega Man X",
"megamanx2": "Mega Man X2",
"megamanx3": "Mega Man X3",
"megamanx4": "Mega Man X4",
"megamanx5": "Mega Man X5",
"megamanx6": "Mega Man X6",
"megamanzero": "Mega Man Zero",
"megamanzx": "Mega Man ZX",
"megaminer": "Mega Miner",
"melonplayground": "Melon Playground",
"meowuwu": "Meow UwU",
"mergeroundracers": "Merge Round Racers",
"metalgear": "Metal Gear",
"metalgearsolid": "Metal Gear Solid",
"metalgearsolidps": "Metal Gear Solid (PS1)",
"metalslug": "Metal Slug",
"metalslug2": "Metal Slug 2",
"metalslugadvance": "Metal Slug Advance",
"metalslugmission1": "Metal Slug Mission 1",
"metalslugmission2": "Metal Slug Mission 2",
"MetalSonicHyperdrive": "Metal Sonic Hyperdrive",
"metroid": "Metroid",
"metroid2": "Metroid II",
"metroidfusion": "Metroid Fusion",
"metroidprimehunters": "Metroid Prime Hunters",
"metroidzeromission": "Metroid: Zero Mission",
"miamishark": "Miami Shark",
"mickeymaniasnes": "Mickey Mania (SNES)",
"microlife": "Micro Life",
"micromages": "Micromages",
"midwaysgreatesthitsn64": "Midway's Greatest Hits (N64)",
"mightyknight": "Mighty Knight",
"mightyknight2": "Mighty Knight 2",
"mimic": "Mimic",
"MinceraftINotMine_V6(1)": "Minceraft",
"MinceraftINotMine_V6": "Minceraft",
"mindscape": "Mindscape",
"mindwave": "Mind Wave",
"minecaves": "Mine Caves",
"minecraft1-8-8": "Minecraft 1.8.8",
"minecraftcasesim": "Minecraft Case Simulator",
"minecraftpocketedition": "Minecraft Pocket Edition",
"minecraftshooter": "Minecraft Shooter",
"MINECRAFTTOWERDEFENSE": "Minecraft Tower Defense",
"mineshooter": "Mine Shooter",
"minesweeperplus": "Minesweeper Plus",
"minhero": "Min Hero",
"minicrossword": "Mini Crossword",
"miniflips": "Mini Flips",
"minimart": "Mini Mart",
"minishooters": "Mini Shooters",
"minitooth": "Mini Tooth",
"miraginewar": "Miragine War",
"misslecommand": "Missile Command",
"mk4ampedup": "Mortal Kombat 4 Amped Up",
"mkmythologiesn64": "Mortal Kombat Mythologies (N64)",
"mktrilogyps1": "Mortal Kombat Trilogy (PS1)",
"mmbn3b": "Mega Man Battle Network 3 Blue",
"mmbn3w": "Mega Man Battle Network 3 White",
"mmbn4bm": "Mega Man Battle Network 4: Blue Moon",
"mmbn4rs": "Mega Man Battle Network 4: Red Sun",
"mmbnws": "Mega Man Battle Network WS",
"mmsf2zxn": "Mega Man Star Force 2: Zerker x Ninja",
"mmsf2zxs": "Mega Man Star Force 2: Zerker x Saurian",
"mmsf3ba": "Mega Man Star Force 3: Black Ace",
"mmsf3rj": "Mega Man Star Force 3: Red Joker",
"mmsfd": "Mega Man Star Force: Dragon",
"mmsfl": "Mega Man Star Force: Leo",
"mmsfp": "Mega Man Star Force: Pegasus",
"mmwilywars": "Mega Man: The Wily Wars",
"mo64(1)": "Mario Odyssey 64",
"mo64": "Mario Odyssey 64",
"mobcontrolhtml5": "Mob Control HTML5",
"mobiusrevolution": "Mobius Revolution",
"Moemon Emerald Vanilla+ (v110)": "Moemon Emerald Vanilla+",
"momimsleeping": "Mom, I'm Sleeping",
"momoscrushers": "Momo's Crushers",
"moneyrush": "Money Rush",
"monkeymart": "Monkey Mart",
"monkeymartenc": "Monkey Mart (Encrypted)",
"monsterderby": "Monster Derby",
"monsterswing": "Monster Swing",
"monstertracks": "Monster Tracks",
"monstertruckcurfew": "Monster Truck Curfew",
"monstertruckportstunt": "Monster Truck Port Stunt",
"moonemeraldextremerandomizer": "Moon Emerald Extreme Randomizer",
"mortalkombat": "Mortal Kombat",
"mortalkombat2": "Mortal Kombat 2",
"mortalkombat2a": "Mortal Kombat 2 (Alt)",
"mortalkombat3": "Mortal Kombat 3",
"mortalkombat3a": "Mortal Kombat 3 (Alt)",
"mortalkombat4": "Mortal Kombat 4",
"mortalkombata": "Mortal Kombat (Alt)",
"mortalkombatadvance": "Mortal Kombat Advance",
"mortkom4": "Mortal Kombat 4",
"motherload": "Motherload",
"motoroadrash": "Moto Road Rash",
"motox3m2": "Moto X3M 2",
"motox3m3": "Moto X3M 3",
"motox3mm": "Moto X3M",
"motox3mpoolparty": "Moto X3M Pool Party",
"motox3mspookyland": "Moto X3M Spooky Land",
"motox3mwinter": "Moto X3M Winter",
"mountainbikeracer": "Mountain Bike Racer",
"mrmine": "Mr. Mine",
"mrracer": "Mr. Racer",
"mspacman (1)": "Ms. Pac-Man",
"mspacman(1)": "Ms. Pac-Man",
"mspacman(2)": "Ms. Pac-Man",
"mspacman": "Ms. Pac-Man",
"multitask": "Multitask",
"mutilate-a-doll": "Mutilate a Doll",
"mvpbaseball": "MVP Baseball",
"mxoffroadmaster": "MX Offroad Master",
"myfriendpedro": "My Friend Pedro",
"myfriendpedroarena": "My Friend Pedro: Arena",
"myteardrop": "My Teardrop",
"n": "N",
"narc": "NARC",
"natsuki64": "Natsuki 64",
"naturalselection": "Natural Selection",
"NautilusOS(1)": "Nautilus OS",
"NautilusOS": "Nautilus OS",
"NBAhangtime": "NBA Hangtime",
"NBAjam": "NBA Jam",
"nbajamTE": "NBA Jam: Tournament Edition",
"nbalive2000": "NBA Live 2000",
"nbalive2003": "NBA Live 2003",
"nblox": "N-Blox",
"neonblaster": "Neon Blaster",
"neonrider": "Neon Rider",
"nesworldchampion": "NES World Champion",
"netattack": "Net Attack",
"neverendinglegacy": "Never Ending Legacy",
"newersmbds": "Newer Super Mario Bros. DS",
"newgroundsrumble": "Newgrounds Rumble",
"newsupermariobros": "New Super Mario Bros.",
"NewSuperMarioWorld2AroundtheWorld": "New Super Mario World 2: Around the World",
"newyorkshark": "New York Shark",
"nextdoor": "Next Door",
"nflblitz": "NFL Blitz",
"nfscarbonowncity": "NFS Carbon: Own the City",
"nfsmostwanted": "Need for Speed: Most Wanted",
"nfsporcheunleashed": "Need for Speed: Porsche Unleashed",
"nfsunderground": "Need for Speed Underground",
"nfsunderground2": "Need for Speed Underground 2",
"ngon(1)": "N-Gon",
"ngon": "N-Gon",
"nhl2002": "NHL 2002",
"nhl98": "NHL 98",
"nhlhitz2003": "NHL Hitz 2003",
"nickelodeonsuperbrawl2": "Nickelodeon Super Brawl 2",
"NicktoonsFreezeFrameFrenzy": "Nicktoons Freeze Frame Frenzy",
"nightcatsurvival": "Night Cat Survival",
"nightclubshowdown": "Nightclub Showdown",
"nightfire": "James Bond 007: Nightfire",
"nightshade": "Nightshade",
"nikehub": "Nike Hub",
"nimrods": "Nimrods",
"ninjabrawl": "Ninja Brawl",
"ninjaobbyparkor": "Ninja Obby Parkour",
"nintendogslab": "Nintendogs Lab",
"nintendoworldcup": "Nintendo World Cup",
"nitclient": "Nit Client",
"nitromemustdie": "Nitrome Must Die",
"nomoregameasdsadfagfggdfs": "No More Games",
"noobminer": "Noob Miner",
"notyourpawn": "Not Your Pawn",
"novaclient": "Nova Client",
"nplus": "N+",
"nsmbuds": "New Super Mario Bros. (NDS)",
"nsmbwds": "New Super Mario Bros. Wii (DS)",
"nubbysnumberfactory": "Nubby's Number Factory",
"nullkevin": "Null Kevin",
"NutsandBoltsScrewingPuzzle": "Nuts and Bolts Screwing Puzzle",
"nzp": "Nazi Zombies Portable",
"obby-99-will-lose": "Obby: 99 Will Lose",
"obby1jumpperclick": "Obby: 1 Jump Per Click",
"obby456": "Obby 456",
"obbybike": "Obby Bike",
"obbycart": "Obby Cart",
"obbyonlyup": "Obby: Only Up",
"obbyrainbowtower": "Obby: Rainbow Tower",
"obbyslide": "Obby Slide",
"obbyswing": "Obby Swing",
"obbyyardsale": "Obby Yard Sale",
"obeythegame": "Obey the Game",
"ocarinaoftimed": "Zelda: Ocarina of Time",
"oddbotout": "Oddbot Out",
"oddfuture": "Odd Future",
"offlineparadise": "Offline Paradise",
"ohflip": "Oh Flip",
"omegalayers": "Omega Layers",
"omeganuggetclicker": "Omega Nugget Clicker",
"omnipresent": "Omnipresent",
"onebitadventure": "One Bit Adventure",
"onenightasfreddy": "One Night as Freddy",
"onepiece": "One Piece",
"onepiecefighting": "One Piece Fighting",
"oneshotold": "One Shot (Old)",
"onlyup": "Only Up",
"OotMasterQuest": "Zelda: Ocarina of Time Master Quest",
"operius": "Operius",
"oppositeday": "Opposite Day",
"opposumcountry": "Opossum Country",
"OrangeRoulette": "Orange Roulette",
"orbofcreation": "Orb of Creation",
"ordinarysonicromhack": "Ordinary Sonic ROM Hack",
"oregontrail": "The Oregon Trail",
"origamiking": "Paper Mario: The Origami King",
"ormm": "Ormm",
"ortalkombat4": "Ortal Kombat 4",
"osu": "Osu!",
"ourpleguy": "Ourple Guy",
"outhold": "Out Hold",
"outnumbered": "Outnumbered",
"OutrunArcade": "Outrun Arcade",
"OutrunGenesis": "Outrun (Genesis)",
"overburden": "Overburden",
"ovo": "OvO",
"ovo2": "OvO 2",
"ovodimensions": "OvO Dimensions",
"ovofixed": "OvO (Fixed)",
"pacman": "Pac-Man",
"pacmana": "Pac-Man (Alt)",
"pacmansuperfast": "Pac-Man Super Fast",
"pacmanworld3": "Pac-Man World 3",
"pacmanworldg": "Pac-Man World (GBA)",
"pacmanworldpsx": "Pac-Man World (PS1)",
"pandameic2": "Pandemic 2",
"papabakeria": "Papa's Bakeria",
"papadonut": "Papa's Donuteria",
"papalouienighthunt2": "Papa Louie Night Hunt 2",
"papalouiewhenburgersattack": "Papa Louie: When Burgers Attack",
"papalouiewhenpizzasattack": "Papa Louie: When Pizzas Attack",
"papalouiewhensundaesattack": "Papa Louie: When Sundaes Attack",
"papapizzagood": "Papa's Pizzeria (Good)",
"papapizzagoody": "Papa's Pizzeria (Goody)",
"papapizzamamamia": "Papa's Pizzeria Mama Mia",
"papasburgerIIIAAAAA": "Papa's Burgeria",
"papascheeseria": "Papa's Cheeseria",
"papascupcakeria": "Papa's Cupcakeria",
"papasfreezeria": "Papa's Freezeria",
"papashotdoggeria": "Papa's Hot Doggeria",
"papaspancakeria": "Papa's Pancakeria",
"papaspastaria": "Papa's Pastaria",
"papasscooperia": "Papa's Scooperia",
"papassushiria": "Papa's Sushiria",
"papastacomia": "Papa's Tacomia",
"papaswingeria": "Papa's Wingeria",
"paperio": "Paper.io",
"paperio3d": "Paper.io 3D",
"paperiomania": "Paper.io Mania",
"papermario": "Paper Mario",
"PaperMarioDSE": "Paper Mario DS Edition",
"PaperMarioPracticeHack": "Paper Mario Practice Hack",
"papermariopromode": "Paper Mario Pro Mode",
"papermariottyd": "Paper Mario: The Thousand-Year Door",
"parappatherapper": "PaRappa the Rapper",
"parappatherapperalt": "PaRappa the Rapper (Alt)",
"parkingfury": "Parking Fury",
"parkingfury2": "Parking Fury 2",
"parkingfury3": "Parking Fury 3",
"parkingrush": "Parking Rush",
"partnersintime": "Mario & Luigi: Partners in Time",
"peacekeeper": "Peacekeeper",
"peach": "Peach",
"peggle": "Peggle",
"penaltykicks": "Penalty Kicks",
"penguindiner": "Penguin Diner",
"penguinpass": "Penguin Pass",
"pepsiman": "Pepsiman",
"pepsimanalt": "Pepsiman (Alt)",
"pereelous": "Perelous",
"perfectdark": "Perfect Dark",
"perfecthotel": "Perfect Hotel",
"persona": "Persona",
"persona2": "Persona 2",
"persona2alt": "Persona 2 (Alt)",
"personaalt": "Persona (Alt)",
"petworld": "Pet World",
"phantasystar": "Phantasy Star",
"phantasystar2": "Phantasy Star II",
"phantasystar3": "Phantasy Star III",
"phantasystar4": "Phantasy Star IV",
"phasma": "Phasma",
"pheonixjusticeforall": "Phoenix Wright: Justice for All",
"pheonixrightaceattorny": "Phoenix Wright: Ace Attorney",
"pheonixtrialsandyear": "Phoenix Wright: Trials and Tribulations",
"pheonixtrialsandyeartrhfasd": "Phoenix Wright: Trials and Tribulations",
"pibbyapocalypse": "Pibby Apocalypse",
"piclient": "Pi Client",
"pico8": "PICO-8",
"pico8edu": "PICO-8 Education",
"picodriller": "Pico Driller",
"picohot": "Pico Hot",
"picolife": "Pico Life",
"piconightpunkin": "Pico Night Punkin",
"picosschool": "Pico's School",
"picovsbeardx": "Pico vs. Bear DX",
"piecesofcake": "Pieces of Cake",
"pikwip": "Pikwip",
"pingpongchaos": "Ping Pong Chaos",
"pinkbike": "Pink Bike",
"pint": "Pint",
"pitfall": "Pitfall",
"pitof100trials": "Pit of 100 Trials",
"pixelbattlegroundsio": "Pixel Battlegrounds.io",
"pixelcombat2": "Pixel Combat 2",
"pixelgun": "Pixel Gun",
"pixelquestlostidols": "Pixel Quest: Lost Idols",
"pixelshooter": "Pixel Shooter",
"pixelspeedrun": "Pixel Speedrun",
"pixelwarfare": "Pixel Warfare",
"pizzapapa": "Pizza Papa",
"pizzatower": "Pizza Tower",
"pkmnarutoans": "Pokemon Naruto Answers",
"planetlife": "Planet Life",
"plangman": "Plangman",
"plantsvszombies": "Plants vs. Zombies",
"plantsvszombiesnds": "Plants vs. Zombies (NDS)",
"plazmaburst": "Plazma Burst",
"plinko": "Plinko",
"plonky": "Plonky",
"pogo3D": "Pogo 3D",
"pokeacademylifeforever": "Pokemon Academy Life Forever",
"pokeallin": "Pokemon All In",
"PokeAmbrosia": "Pokemon Ambrosia",
"pokebattlefact": "Pokemon Battle Factory",
"pokeblack": "Pokemon Black",
"pokeblack2alt": "Pokemon Black 2 (Alt)",
"pokeblack2html": "Pokemon Black 2 (HTML)",
"pokeblackalt": "Pokemon Black (Alt)",
"pokeblazeblack2redux": "Pokemon Blaze Black 2 Redux",
"pokeblue": "Pokemon Blue",
"pokeclassic": "Pokemon Classic",
"pokecrown": "Pokemon Crown",
"pokecrystaladvanceredux": "Pokemon Crystal Advance Redux",
"pokecrystalclear": "Pokemon Crystal Clear",
"pokediamond": "Pokemon Diamond",
"pokedreamstone": "Pokemon Dreamstone",
"pokeeliteredux": "Pokemon Elite Redux",
"pokeelysiuma": "Pokemon Elysium A",
"pokeelysiumb": "Pokemon Elysium B",
"pokeemeraldenhanced": "Pokemon Emerald Enhanced",
"pokeemeraldexceeded": "Pokemon Emerald Exceeded",
"pokeemeraldhorizons": "Pokemon Emerald Horizons",
"pokeemeraldimperium": "Pokemon Emerald Imperium",
"pokeemeraldrandom": "Pokemon Emerald (Randomized)",
"pokeemeraldrogue": "Pokemon Emerald Rogue",
"PokeEmeraldRogueEX": "Pokemon Emerald Rogue EX",
"pokeemeraldz": "Pokemon Emerald Z",
"pokefiregold": "Pokemon Fire Gold",
"pokeflora": "Pokemon Flora",
"pokefrlgplus": "Pokemon FR/LG Plus",
"pokefuseddimension": "Pokemon Fused Dimension",
"PokeFusion3": "Pokemon Fusion 3",
"pokegaia": "Pokemon Gaia",
"pokegoldenshield": "Pokemon Golden Shield",
"pokegschronicles": "Pokemon GS Chronicles",
"pokeheartgold": "Pokemon HeartGold",
"PokeHeartgoldGenerations": "Pokemon HeartGold Generations",
"pokelightplatinum": "Pokemon Light Platinum",
"pokeliquidcrysta": "Pokemon Liquid Crystal",
"pokemegamoemon": "Pokemon Mega Moemon",
"pokemonamnesia": "Pokemon Amnesia",
"pokemonclover": "Pokemon Clover",
"pokemoncrystal": "Pokemon Crystal",
"pokemonemerald": "Pokemon Emerald",
"pokemonemeraldcrest": "Pokemon Emerald Crest",
"pokemonemeraldimperium": "Pokemon Emerald Imperium",
"pokemonemeraldkaizo": "Pokemon Emerald Kaizo",
"pokemonemeraldmini": "Pokemon Emerald Mini",
"Pokemonemeraldrouge": "Pokemon Emerald Rouge",
"pokemonemeraldseaglass": "Pokemon Emerald Sea Glass",
"pokemonenergizedemerald": "Pokemon Energized Emerald",
"pokemonevolvedsfdgsdfs": "Pokemon Evolved",
"pokemonfirered": "Pokemon Fire Red",
"pokemonfireredandleafgreenplusedition": "Pokemon Fire Red & Leaf Green Plus Edition",
"pokemonfireredrandomized": "Pokemon Fire Red (Randomized)",
"pokemongold": "Pokemon Gold",
"pokemonkaizoironfirered": "Pokemon Kaizo Iron Fire Red",
"pokemonlazarus": "Pokemon Lazarus",
"pokemonleafgreen": "Pokemon Leaf Green",
"pokemonmodernemerald": "Pokemon Modern Emerald",
"pokemonmysterydungeon": "Pokemon Mystery Dungeon",
"pokemonperfectemerald55": "Pokemon Perfect Emerald",
"pokemonquetzal": "Pokemon Quetzal",
"pokemonroaringred": "Pokemon Roaring Red",
"Pokemonrocketedition": "Pokemon Rocket Edition",
"pokemonruby": "Pokemon Ruby",
"pokemonsaiph": "Pokemon Saiph",
"pokemonsaiph2": "Pokemon Saiph 2",
"pokemonsapphire": "Pokemon Sapphire",
"pokemonshinsigma": "Pokemon Shin Sigma",
"pokemonsilver": "Pokemon Silver",
"pokemonslgreen": "Pokemon Leaf Green (Alt)",
"pokemonsmred": "Pokemon Fire Red (Alt)",
"pokemonsnap": "Pokemon Snap",
"pokemonsors": "Pokemon SoRS",
"pokemonsors2": "Pokemon SoRS 2",
"pokemonstadium": "Pokemon Stadium",
"pokemonstadium2": "Pokemon Stadium 2",
"pokemontowerdefense": "Pokemon Tower Defense",
"pokemonultimatefusion": "Pokemon Ultimate Fusion",
"pokemonunbound": "Pokemon Unbound",
"pokemonvolume1": "Pokemon Volume 1",
"pokemonvolume2": "Pokemon Volume 2",
"pokemonvolume3": "Pokemon Volume 3",
"pokemonvolume4": "Pokemon Volume 4",
"pokemoonemerald": "Pokemon Moon Emerald",
"pokemongalaxy": "Pokemon Galaxy",
"pokemysteryexplorersofsky": "Pokemon Mystery Dungeon: Explorers of Sky",
"pokenameless": "Pokemon Nameless",
"pokeodyssey": "Pokemon Odyssey",
"pokepasta": "Pokemon Pasta",
"pokepath": "Pokemon Path",
"pokepearl": "Pokemon Pearl",
"pokeperfectfirered": "Pokemon Perfect Fire Red",
"pokepisces": "Pokemon Pisces",
"pokeplatinum": "Pokemon Platinum",
"pokeplatinumrandomized": "Pokemon Platinum (Randomized)",
"pokepureblue": "Pokemon Pure Blue",
"pokepuregreen": "Pokemon Pure Green",
"pokepurered": "Pokemon Pure Red",
"pokerechargedpink": "Pokemon Recharged Pink",
"pokerechargedyellow": "Pokemon Recharged Yellow",
"pokerecordkeepers": "Pokemon Record Keepers",
"pokered": "Pokemon Red",
"pokerenegadeplat": "Pokemon Renegade Platinum",
"pokerocketedition": "Pokemon Rocket Edition",
"pokerowe": "Pokemon Rowe",
"pokeruby": "Pokemon Ruby",
"pokerunandbun": "Pokemon Run and Bun",
"pokescorchedsilver": "Pokemon Scorched Silver",
"pokesoulsilver": "Pokemon SoulSilver",
"pokesunsky": "Pokemon Sun Sky",
"poketcg1": "Pokemon TCG",
"poketcg2": "Pokemon TCG 2",
"pokethepit": "Pokemon: The Pit",
"PokeThetaEmeraldEX": "Pokemon Theta Emerald EX",
"poketoomanytypes2": "Pokemon Too Many Types 2",
"poketourmaline": "Pokemon Tourmaline",
"pokeultraviolet": "Pokemon Ultraviolet",
"pokeunovaemerald": "Pokemon Unova Emerald",
"pokevega": "Pokemon Vega",
"pokevoltwhite2redux": "Pokemon Volt White 2 Redux",
"pokevoyager": "Pokemon Voyager",
"pokewhite": "Pokemon White",
"pokewhite2": "Pokemon White 2",
"pokewhite2alt": "Pokemon White 2 (Alt)",
"pokeyellow": "Pokemon Yellow",
"policepursuit2": "Police Pursuit 2",
"polishedcrystal": "Pokemon Polished Crystal",
"polytrackbutnotflagged(1)": "Polytrack",
"polytrackbutnotflagged": "Polytrack",
"polytrackworksnow": "Polytrack",
"pomgetsinternet": "Pom Gets Wi-Fi",
"poorbunny": "Poor Bunny",
"popeyepapi": "Popeye PAPI",
"porklike": "Porklike",
"portal": "Portal",
"portal2d": "Portal 2D",
"portaldefendersfastbreak": "Portal Defenders: Fast Break",
"portaldefendersTD": "Portal Defenders TD",
"portalflash": "Portal Flash",
"porter": "Porter",
"portraitofruin": "Castlevania: Portrait of Ruin",
"possessquest": "Possess Quest",
"postal": "Postal",
"potatomanseeksthetroof": "Potato Man Seeks the Troof",
"pou(1)": "Pou",
"Pou": "Pou",
"powerslave": "Powerslave",
"praxisfighterx": "Praxis Fighter X",
"prebronzeage": "Pre-Bronze Age",
"precivilationbronzeage": "Pre-Civilization Bronze Age",
"prehistoricshark": "Prehistoric Shark",
"primary": "Primary",
"prismarine": "Prismarine",
"processortycoon": "Processor Tycoon",
"professorlaytonandthecuriousvillage": "Professor Layton and the Curious Village",
"puckman": "Puck Man",
"pullfrog": "Pull Frog",
"pumpkinrun": "Pumpkin Run",
"punchout": "Punch-Out!!",
"punchthedrump": "Punch the Drump",
"punchthetrump": "Punch the Trump",
"puppethockey": "Puppet Hockey",
"puppetmaster": "Puppet Master",
"pushyourluck": "Push Your Luck",
"puyopuyofever": "Puyo Puyo Fever",
"pvz": "Plants vs. Zombies",
"pvz2": "Plants vs. Zombies 2",
"pvz2gardenless": "Plants vs. Zombies 2 (Gardenless)",
"PVZM": "Plants vs. Zombies Merged",
"pyrotoad": "Pyrotoad",
"qbert": "Q*bert",
"qbertarcade": "Q*bert Arcade",
"qtrewired": "Qtre Wired",
"quake2": "Quake II",
"quake3": "Quake III",
"quake64": "Quake 64",
"QuantumClicker": "Quantum Clicker",
"quickieworld": "Quickie World",
"qwop": "QWOP",
"racemaster3d": "Race Master 3D",
"racingarena": "Racing Arena",
"radicalred": "Pokemon Radical Red",
"radracer": "Rad Racer",
"raftwars": "Raft Wars",
"raftwars2": "Raft Wars 2",
"ragdoll-io": "Ragdoll.io",
"ragdollachivement": "Ragdoll Achievement",
"ragdollarchers": "Ragdoll Archers",
"ragdolldrop": "Ragdoll Drop",
"ragdollhit": "Ragdoll Hit",
"ragdollrunners": "Ragdoll Runners",
"ragdollsoccer": "Ragdoll Soccer",
"ragollhit": "Ragdoll Hit",
"rainbowsix": "Rainbow Six",
"rainbowsixalt": "Rainbow Six (Alt)",
"raldiscrackhouse": "Raldi's Crackhouse",
"ravenbase": "Raven Base",
"ray1": "Ray 1",
"ray2": "Ray 2",
"rayman": "Rayman",
"raze": "Raze",
"raze2": "Raze 2",
"raze3": "Raze 3",
"re3": "Resident Evil 3",
"reachthecore": "Reach the Core",
"realflightsim": "Real Flight Simulator",
"rebuild": "Rebuild",
"rebuild2": "Rebuild 2",
"recoil": "Recoil",
"redalert": "Command & Conquer: Red Alert",
"redball": "Red Ball",
"redball2": "Red Ball 2",
"redball3": "Red Ball 3",
"redball4(1)": "Red Ball 4",
"RedBall4": "Red Ball 4",
"redball4vol2": "Red Ball 4 Vol. 2",
"redball4vol3": "Red Ball 4 Vol. 3",
"redhanded": "Red Handed",
"redtierunner": "Red Tie Runner",
"redvbluefix": "Red vs. Blue (Fix)",
"redvsblue2": "Red vs. Blue 2",
"redvsbluewar": "Red vs. Blue War",
"reignofcentipede": "Reign of Centipede",
"renegades": "Renegades",
"repobad": "Repo Bad",
"residentevil": "Resident Evil",
"residentevil2": "Resident Evil 2",
"residentevil2d1": "Resident Evil 2D Part 1",
"residentevil2d2": "Resident Evil 2D Part 2",
"resizer": "Resizer",
"resortempire": "Resort Empire",
"retrobowl": "Retro Bowl",
"retrobowlcollege": "Retro Bowl College",
"retrohighway": "Retro Highway",
"retropingpong": "Retro Ping Pong",
"returnman": "Return Man",
"returnman2": "Return Man 2",
"returntoriddleschool": "Return to Riddle School",
"revolutionidle": "Revolution Idle",
"rewrite2": "Rewrite 2",
"rh": "RH",
"rhythmheaven": "Rhythm Heaven",
"rhythymymheaven": "Rhythm Heaven",
"ricochetkills2": "Ricochet Kills 2",
"riddle": "Riddle",
"riddlemiddleschool": "Riddle Middle School",
"riddleschool": "Riddle School",
"riddleschool2": "Riddle School 2",
"riddleschool3": "Riddle School 3",
"riddleschool445544444$$444$444": "Riddle School 4",
"riddletransfer": "Riddle Transfer",
"riddletransfer2": "Riddle Transfer 2",
"riddleuneversityfix": "Riddle University (Fix)",
"ridgeracer": "Ridge Racer",
"risehigher": "Rise Higher",
"ristar": "Ristar",
"roadfighter": "Road Fighter",
"roadoffury": "Road of Fury",
"roadofthedead": "Road of the Dead",
"roadofthedead2": "Road of the Dead 2",
"roadrunnernes": "Road Runner (NES)",
"rocketgoalio": "Rocket Goal.io",
"rocketjump": "Rocket Jump",
"rocketknight2 (1)": "Rocket Knight 2",
"rocketknight2(1)": "Rocket Knight 2",
"rocketknight2(2)": "Rocket Knight 2",
"rocketknight2": "Rocket Knight 2",
"rocketknightadventures": "Rocket Knight Adventures",
"rocketleague": "Rocket League",
"rocketpult": "Rocketpult",
"rocketsoccerderby": "Rocket Soccer Derby",
"rodha": "Rodha",
"roguesoul": "Rogue Soul",
"roguesoul2": "Rogue Soul 2",
"rollerballer": "Rollerballer",
"rollingsky": "Rolling Sky",
"rollyvortex": "Rolly Vortex",
"rolypolymonster": "Roly Poly Monster",
"rooftoprun": "Rooftop Run",
"rooftopsnipers": "Rooftop Snipers",
"rooftopsnipers2": "Rooftop Snipers 2",
"roomclicker": "Room Clicker",
"rosegold": "Rose Gold",
"rotate": "Rotate",
"roulettehero": "Roulette Hero",
"rouletteknight": "Roulette Knight",
"ruffle": "Ruffle",
"run-2": "Run 2",
"run": "Run",
"run2": "Run 2",
"run3": "Run 3",
"runningfred": "Running Fred",
"russianbuckshot": "Russian Buckshot",
"russiancardriver": "Russian Car Driver",
"russiansandbox": "Russian Sandbox",
"saihatestation": "Saihate Station",
"sandboxcity": "Sandbox City",
"sandboxels": "Sandboxels",
"sandsofthecoliseum": "Sands of the Coliseum",
"sandstone(1)": "Sandstone",
"sandstone": "Sandstone",
"sandtris": "Sandtris",
"santarun": "Santa Run",
"santy": "Santy",
"saszombieassault2": "SAS: Zombie Assault 2",
"satryn": "Satryn",
"saulgoodmanrun": "Saul Goodman Run",
"sausageflip": "Sausage Flip",
"sayorisnotebook": "Sayori's Notebook",
"scalethedepths": "Scale the Depths",
"ScamptonTheGreatFightRecreate": "Scampton: The Great Fight Recreate",
"scarletandviolet": "Pokemon Scarlet and Violet",
"scarletshift": "Scarlet Shift",
"scarymaze": "Scary Maze Game",
"scarymazegame": "Scary Maze Game",
"scaryshawarma": "Scary Shawarma",
"scaryteacher3d": "Scary Teacher 3D",
"schoolboyrunaway": "Schoolboy Runaway",
"scrapmetal3": "Scrap Metal 3",
"scrapyarddog": "Scrapyard Dog",
"scratcoptions": "Scratch Options",
"scratchoptions": "Scratch Options",
"scribblenauts": "Scribblenauts",
"scubabear": "Scuba Bear",
"sd-thewar": "SD: The War",
"sdf": "SDF",
"seamongrel": "Sea Mongrel",
"secretofmana": "Secret of Mana",
"sega2gg": "Sega 2 GG",
"SegaSonicTheHedgehog": "Sega Sonic the Hedgehog",
"self": "Self",
"sentryfortress": "Sentry Fortress",
"serenitrove": "Serenitrove",
"serioussamadvance": "Serious Sam Advance",
"servingupmadness": "Serving Up Madness",
"sevendays": "Seven Days",
"sfk": "Strike Force Kitty",
"sfk2": "Strike Force Kitty 2",
"sfklaststand": "Strike Force Kitty: Last Stand",
"sfkleague": "Strike Force Kitty League",
"shadowcourier": "Shadow Courier",
"shadowdancer": "Shadow Dancer",
"shadowdancersecret": "Shadow Dancer Secret",
"shaggy (1)": "Shaggy",
"shaggy": "Shaggy",
"shantaegb": "Shantae (GB)",
"shapetransform": "Shape Transform",
"shc1": "SHC 1",
"shc2": "SHC 2",
"shc3": "SHC 3",
"shift": "Shift",
"shift2": "Shift 2",
"shift3": "Shift 3",
"shiftatmidnight": "Shift at Midnight",
"shinmegamitenseidevilsurvivor": "Shin Megami Tensei: Devil Survivor",
"shinobi": "Shinobi",
"shinobi3": "Shinobi III",
"shinobirevenge": "Shinobi's Revenge",
"shoppingcarthero": "Shopping Cart Hero",
"shortlife": "Short Life",
"shotout4": "Shot Out 4",
"shredmill": "Shredmill",
"shredsauce": "Shred Sauce",
"shrek-2": "Shrek 2",
"shrubnaut": "Shrubnaut",
"shwultimatem": "SHW Ultimate M",
"sideeffects": "Side Effects",
"sidepocket": "Side Pocket",
"sierra7": "Sierra 7",
"silenthill": "Silent Hill",
"silenthillalt": "Silent Hill (Alt)",
"silk": "Silk",
"silkmelody": "Silk Melody",
"siloshowdow": "Silo Showdown",
"silver": "Silver",
"simcity64": "SimCity 64",
"simpsonsarcade": "The Simpsons Arcade",
"SINGLEFILE": "Single File",
"sixwaystodie": "Six Ways to Die",
"skateit": "Skate It",
"skateordie": "Skate or Die",
"skibididibidygyattohiorizzingallovertheplacestillwatermangotheoryfemboydrool": "Skibidi Ohio Rizz",
"skibidiinthebackrooms": "Skibidi in the Backrooms",
"skibidishooter": "Skibidi Shooter",
"skinwalker": "Skinwalker",
"skong": "Skong",
"skyrace-3d": "Sky Race 3D",
"SkyRiders": "Sky Riders",
"skywire": "Skywire",
"skywire2": "Skywire 2",
"slenderman": "Slenderman",
"slendytubbies": "Slendytubbies",
"sliceitall": "Slice It All",
"slideinthewoods": "Slide in the Woods",
"slimelabratory": "Slime Laboratory",
"slipways": "Slipways",
"slitherio": "Slither.io",
"slope": "Slope",
"slope2player": "Slope 2 Player",
"slope3": "Slope 3",
"slopeplus": "Slope Plus",
"slotornot": "Slot or Not",
"slowroads": "Slow Roads",
"sm63redux": "Super Mario 63 Redux",
"sm64greenstars": "Super Mario 64: Green Stars",
"sm64hiddenstars": "Super Mario 64: Hidden Stars",
"SM64Land": "Super Mario 64 Land",
"sm64lastimpact": "Super Mario 64: Last Impact",
"sm64liminaldream": "Super Mario 64: Liminal Dream",
"sm64oot": "Super Mario 64 x OoT",
"sm64sapphire": "Super Mario 64 Sapphire",
"smadvance2": "Super Mario Advance 2",
"smadvance3": "Super Mario Advance 3",
"Smash Hit Ripoff": "Smash Hit Ripoff",
"smashkarts": "Smash Karts",
"smashkartsworking": "Smash Karts (Working)",
"smashremix": "Smash Remix",
"smashremix201": "Smash Remix 2.01",
"smb12": "Super Mario Bros. 1 & 2",
"smbc": "Super Mario Bros. Crossover",
"smbcrossover": "Super Mario Bros. Crossover",
"smbgameover": "Super Mario Bros. Game Over",
"smbremastered": "Super Mario Bros. Remastered",
"smc": "SMC",
"smgds": "Super Mario Galaxy DS",
"snailbob": "Snail Bob",
"snailbob2": "Snail Bob 2",
"snailbob3": "Snail Bob 3",
"snailbob4space": "Snail Bob 4: Space",
"snailbob5lovestory": "Snail Bob 5: Love Story",
"snakeis": "Snake Is",
"snakelike": "Snakelike",
"snipershot": "Sniper Shot",
"sniperv2": "Sniper v2",
"snowballio": "Snowball.io",
"snowboardobby": "Snowboard Obby",
"snowbros (1)": "Snow Bros.",
"snowbros(1)": "Snow Bros.",
"snowbros(2)": "Snow Bros.",
"snowbros": "Snow Bros.",
"SnowBrosGenesis": "Snow Bros. (Genesis)",
"snowbrothers": "Snow Brothers",
"snowdrift": "Snow Drift",
"snowrid": "Snow Ride",
"snowrideee": "Snow Rider",
"snowrider": "Snow Rider 3D",
"snowridergoodygumdrops": "Snow Rider (Goody Gumdrops)",
"snowriderrrr": "Snow Rider",
"snowroad": "Snow Road",
"snowwhite": "Snow White",
"soccerbros": "Soccer Bros",
"soccerrandom": "Soccer Random",
"soccerrandomgood": "Soccer Random (Good)",
"sodasimulator": "Soda Simulator",
"solarsandbox": "Solar Sandbox",
"solarsmash": "Solar Smash",
"solatrobo": "Solatorobo",
"solitaire": "Solitaire",
"solstice": "Solstice",
"somari64": "Somari 64",
"Sonic & Knuckles + Sonic The Hedgehog 3": "Sonic 3 & Knuckles",
"sonic1contemporary": "Sonic 1 Contemporary",
"sonic1mobile": "Sonic 1 Mobile",
"Sonic1ScoreRush": "Sonic 1 Score Rush",
"Sonic1TheSuperChallenges": "Sonic 1: The Super Challenges",
"sonic2mobile": "Sonic 2 Mobile",
"sonic2pinkedition": "Sonic 2 Pink Edition",
"Sonic2ScoreRush": "Sonic 2 Score Rush",
"sonic2timeandplace": "Sonic 2: Time and Place",
"sonic3andknuckles": "Sonic 3 & Knuckles",
"sonic3andsally": "Sonic 3 and Sally",
"sonic3complete": "Sonic 3 Complete",
"sonic3dblast": "Sonic 3D Blast",
"sonic3dblastdx": "Sonic 3D Blast DX",
"sonicadvance": "Sonic Advance",
"sonicadvance2": "Sonic Advance 2",
"sonicadvance2sp": "Sonic Advance 2 SP",
"sonicadvance3": "Sonic Advance 3",
"sonicandashuro": "Sonic and Ashuro",
"sonicandfallingstar": "Sonic and the Falling Star",
"sonicandknuckles": "Sonic & Knuckles",
"sonicbattle": "Sonic Battle",
"sonicblast": "Sonic Blast",
"soniccd": "Sonic CD",
"soniccdmobile": "Sonic CD Mobile",
"sonicchaos": "Sonic Chaos",
"sonicclassiccollection": "Sonic Classic Collection",
"sonicclassicheroes(1)": "Sonic Classic Heroes",
"sonicclassicheroes": "Sonic Classic Heroes",
"SonicClassics": "Sonic Classics",
"soniccolors": "Sonic Colors",
"sonicdeltaorigins": "Sonic Delta Origins",
"soniceexeog": "Sonic.exe OG",
"sonicerazor": "Sonic Razor",
"sonicgg": "Sonic (Game Gear)",
"SonicHellfireSaga": "Sonic Hellfire Saga",
"SonicInSM64": "Sonic in SM64",
"SonicinSMW(1)": "Sonic in SMW",
"sonicinsmw(2)": "Sonic in SMW",
"SonicinSMW": "Sonic in SMW",
"sonicjam": "Sonic Jam",
"soniclabyrinth": "Sonic Labyrinth",
"sonicmania": "Sonic Mania",
"sonicmaniaplus": "Sonic Mania Plus",
"sonicmegamix": "Sonic Mega Mix",
"sonicmon": "Sonic Mon",
"sonicpocketadventure": "Sonic Pocket Adventure",
"sonicr": "Sonic R",
"sonicralt": "Sonic R (Alt)",
"sonicrevert": "Sonic Revert",
"sonicrush": "Sonic Rush",
"sonicrushadventure": "Sonic Rush Adventure",
"sonicscorchedquest": "Sonic Scorched Quest",
"sonicspinball": "Sonic Spinball",
"sonicthehedgehog": "Sonic the Hedgehog",
"sonicthehedgehog2": "Sonic the Hedgehog 2",
"sonicthehedgehog3": "Sonic the Hedgehog 3",
"sonny2": "Sonny 2",
"sortthecourt": "Sort the Court",
"sotn": "Castlevania: Symphony of the Night",
"souljumper": "Soul Jumper",
"soundboard": "Soundboard",
"southparkn64": "South Park (N64)",
"Sovereignoftheskys": "Sovereign of the Skies",
"spacebarclicker": "Spacebar Clicker",
"spacecompany": "Space Company",
"spaceharriersms": "Space Harrier (SMS)",
"spaceinvade95": "Space Invaders '95",
"spaceinvaders": "Space Invaders",
"spaceiskey": "Space is Key",
"spaceiskey2": "Space is Key 2",
"spaceiskeyxmas": "Space is Key Xmas",
"spacewarsbattleground": "Space Wars Battleground",
"spacewaves": "Space Waves",
"specialmission": "Special Mission",
"speedperclick": "Speed Per Click",
"speedstars": "Speed Stars",
"spelunky": "Spelunky",
"spewer": "Spewer",
"spidermanps1": "Spider-Man (PS1)",
"spiralroll": "Spiral Roll",
"spiritsofhell": "Spirits of Hell",
"SpongebobPowerKartGrandPrix": "SpongeBob Power Kart Grand Prix",
"SportsHeadsIceHockey": "Sports Heads: Ice Hockey",
"sprinter": "Sprinter",
"sprunked": "Sprunked",
"sprunki": "Sprunki",
"sprunkiclicker": "Sprunki Clicker",
"spyhunter": "Spy Hunter",
"squidplayground": "Squid Playground",
"SSF2Arcade": "Super Street Fighter II Arcade",
"SSF2TArcade": "Super Street Fighter II Turbo Arcade",
"stackballio": "Stack Ball.io",
"stacktris": "Stack Tris",
"stackydash": "Stacky Dash",
"starfox": "Star Fox",
"starfox64": "Star Fox 64",
"starraiders": "Star Raiders",
"stateio": "State.io",
"station141": "Station 141",
"stationmeltdown": "Station Meltdown",
"stationsaturn": "Station Saturn",
"steakandjake": "Steak and Jake",
"stealbrainrot": "Steal Brainrot",
"stealbrainrotonline": "Steal Brainrot Online",
"stealthassassin": "Stealth Assassin",
"stealthmaster": "Stealth Master",
"steelempire": "Steel Empire",
"steelsurge": "Steel Surge",
"steepdescent": "Steep Descent",
"stickarchersbattle": "Stick Archers Battle",
"stickdefenders": "Stick Defenders",
"stickfighter": "Stick Fighter",
"stickjetchallenge": "Stick Jet Challenge",
"stickmanandguns": "Stickman and Guns",
"stickmanclash": "Stickman Clash",
"stickmanduel": "Stickman Duel",
"stickmangtacity": "Stickman GTA City",
"stickmanhook": "Stickman Hook",
"StickmanKingdomclash": "Stickman Kingdom Clash",
"stickmankombat2d": "Stickman Kombat 2D",
"stickmanstealingdiamond": "Stickman Stealing Diamond",
"stickmerge": "Stick Merge",
"stickminairship": "Stickmin: Airship",
"stickminbreakingbank": "Stickmin: Breaking the Bank",
"stickminescapingprison": "Stickmin: Escaping the Prison",
"stickminfleecomplex": "Stickmin: Fleeing the Complex",
"stickrpgcomplete": "Stick RPG Complete",
"stickslasher": "Stick Slasher",
"stickwar": "Stick War",
"stickwar2": "Stick War 2",
"stickwithit": "Stick With It",
"stormthehouse": "Storm the House",
"stormthehouse2": "Storm the House 2",
"stormthehouse3": "Storm the House 3",
"strangejournet": "Strange Journey",
"streangeropepolice": "Strange Rope Police",
"StreetFighter1Arcade": "Street Fighter Arcade",
"streetfighter2": "Street Fighter II",
"StreetFighter2Arcade": "Street Fighter II Arcade",
"StreetFighter2CEArcade": "Street Fighter II Champion Edition Arcade",
"StreetFighter2HFArcade(1)": "Street Fighter II Hyper Fighting Arcade",
"StreetFighter2HFArcade": "Street Fighter II Hyper Fighting Arcade",
"streetfighter2turbo": "Street Fighter II Turbo",
"streetfighteralpha3": "Street Fighter Alpha 3",
"streetfighterumuhsomething": "Street Fighter",
"streetofrage": "Streets of Rage",
"streetofrage2": "Streets of Rage 2",
"streetofrage3": "Streets of Rage 3",
"strikeforceheroes": "Strike Force Heroes",
"strikeforceheroes2": "Strike Force Heroes 2",
"strikeforceheroes3": "Strike Force Heroes 3",
"strikerdummies": "Striker Dummies",
"stylesavvy": "Style Savvy",
"subwaysurfersbarcelona": "Subway Surfers: Barcelona",
"subwaysurfersbeijing": "Subway Surfers: Beijing",
"subwaysurfersberlin": "Subway Surfers: Berlin",
"subwaysurfersbuenosaires": "Subway Surfers: Buenos Aires",
"subwaysurfershavana": "Subway Surfers: Havana",
"subwaysurfershouston": "Subway Surfers: Houston",
"subwaysurfersiceland": "Subway Surfers: Iceland",
"subwaysurferslondon": "Subway Surfers: London",
"subwaysurfersmexico": "Subway Surfers: Mexico",
"subwaysurfersmiami": "Subway Surfers: Miami",
"subwaysurfersmonaco": "Subway Surfers: Monaco",
"subwaysurfersneworeleans": "Subway Surfers: New Orleans",
"subwaysurfersneworleans": "Subway Surfers: New Orleans",
"subwaysurferssanfrancisco (1)": "Subway Surfers: San Francisco",
"subwaysurferssanfrancisco(1)": "Subway Surfers: San Francisco",
"subwaysurferssanfrancisco": "Subway Surfers: San Francisco",
"subwaysurfersstpetersburg": "Subway Surfers: St. Petersburg",
"subwaysurferswinterholiday": "Subway Surfers: Winter Holiday",
"subwaysurferszurich": "Subway Surfers: Zurich",
"sugarsugar": "Sugar Sugar",
"suika": "Suika Game",
"suikapico": "Suika PICO",
"summerrider": "Summer Rider",
"sunandmoon": "Sun and Moon",
"superbomberman": "Super Bomberman",
"superbomberman2": "Super Bomberman 2",
"superbomberman3": "Super Bomberman 3",
"superbomberman4": "Super Bomberman 4",
"superbomberman5": "Super Bomberman 5",
"superc": "Super C",
"supercarrush": "Super Car Rush",
"supercastlevaniaVI": "Super Castlevania IV",
"superchibiknight": "Super Chibi Knight",
"supercold": "Super Cold",
"superdarkdeception": "Super Dark Deception",
"superdiagonalmario2": "Super Diagonal Mario 2",
"superdromebugs(1)": "Super Drome Bugs",
"superdromebugs": "Super Drome Bugs",
"superfallingfred": "Super Falling Fred",
"superfighters": "Super Fighters",
"superhot": "Superhot",
"superhotlinemiami": "Super Hotline Miami",
"superhouseofdeadninjas": "Super House of Dead Ninjas",
"superislandadventure": "Super Island Adventure",
"superliquidsoccer": "Super Liquid Soccer",
"supermario": "Super Mario",
"supermario3mix": "Super Mario 3 Mix",
"supermario63": "Super Mario 63",
"supermario64": "Super Mario 64",
"supermario64ds": "Super Mario 64 DS",
"supermario74": "Super Mario 74",
"supermarioallstars": "Super Mario All-Stars",
"supermariobros": "Super Mario Bros.",
"supermariobros2": "Super Mario Bros. 2",
"supermariobros2us": "Super Mario Bros. 2 (US)",
"supermariobros3": "Super Mario Bros. 3",
"supermariobros3real": "Super Mario Bros. 3 (Real)",
"supermariokart": "Super Mario Kart",
"supermarioland": "Super Mario Land",
"supermarioland2": "Super Mario Land 2",
"supermarioland2dx": "Super Mario Land 2 DX",
"supermariolanddx": "Super Mario Land DX",
"supermariomon": "Super Mario Mon",
"supermariorpg": "Super Mario RPG",
"supermariostarroad": "Super Mario Star Road",
"supermariostarroadretooled": "Super Mario Star Road Retooled",
"supermariosunshine64": "Super Mario Sunshine 64",
"supermarioworld": "Super Mario World",
"supermarioworld2": "Super Mario World 2",
"SuperMarioWorldThe SecretOfThe7GoldenStatues": "Super Mario World: The Secret of the 7 Golden Statues",
"supermetroid": "Super Metroid",
"supermonkeyballjr": "Super Monkey Ball Jr.",
"supernoahsark3D": "Super Noah's Ark 3D",
"superoliverworld": "Super Oliver World",
"superonionboy2": "Super Onion Boy 2",
"superpickleballadventure": "Super Pickleball Adventure",
"superpunchout": "Super Punch-Out!!",
"SuperPunchOutEN": "Super Punch-Out!! (EN)",
"superpuzzlefighter2turbo": "Super Puzzle Fighter II Turbo",
"superpuzzlefighter2turboalt": "Super Puzzle Fighter II Turbo (Alt)",
"supersantakicker": "Super Santa Kicker",
"supersantakicker2": "Super Santa Kicker 2",
"superscribblenauts": "Super Scribblenauts",
"supersmashbros": "Super Smash Bros.",
"supersmashflash": "Super Smash Flash",
"supersmashflash08": "Super Smash Flash '08",
"supersmashflash2": "Super Smash Flash 2",
"supersmashflash2butdifversion": "Super Smash Flash 2 (Alt)",
"superstreetfighter2turbojp": "Super Street Fighter II Turbo (JP)",
"supertiltbros": "Super Tilt Bros.",
"supitdept": "Supit Dept",
"supremeduelist": "Supreme Duelist",
"SupremeDuelist2019": "Supreme Duelist 2019",
"survivalracev2": "Survival Race v2",
"survivorio": "Survivor.io",
"sushicat": "Sushi Cat",
"sushicat2": "Sushi Cat 2",
"sushiunroll": "Sushi Unroll",
"swerve": "Swerve",
"switchblade": "Switchblade",
"swordandshieldultimateplus": "Pokemon Sword and Shield Ultimate Plus",
"swordfight": "Sword Fight",
"swordplay": "Swordplay",
"swordsandsandals": "Swords and Sandals",
"swordsandsandals2": "Swords and Sandals 2",
"swordsandsouls": "Swords and Souls",
"sydneyshark": "Sydney Shark",
"tabi": "Tabi",
"tabletanks": "Table Tanks",
"tabletennisworldtour": "Table Tennis World Tour",
"tacostand": "Taco Stand",
"tag-": "Tag",
"tagc3": "Tag C3",
"tagcm": "Tag CM",
"TaikonoTatsujin": "Taiko no Tatsujin",
"tailofthedragon": "Tail of the Dragon",
"taisei": "Taisei",
"takeover": "Takeover",
"tallio": "Tall.io",
"tallmanrun": "Tall Man Run",
"tankmayhem": "Tank Mayhem",
"tankpixel": "Tank Pixel",
"tanktrouble": "Tank Trouble",
"tanukisunset": "Tanuki Sunset",
"tanukisunsetuhhhhhhhh": "Tanuki Sunset",
"tapper": "Tapper",
"taproad": "Tap Road",
"tastyplanet": "Tasty Planet",
"tboidemo": "TBOI Demo",
"tboilambeternal": "Binding of Isaac: Lamb Eternal",
"tecmobowl": "Tecmo Bowl",
"tekken2ps1": "Tekken 2 (PS1)",
"tekken3ps1": "Tekken 3 (PS1)",
"telephonetrouble": "Telephone Trouble",
"telocation": "Telocation",
"tempest2000": "Tempest 2000",
"templeofboom": "Temple of Boom",
"templerun2": "Temple Run 2",
"tempoverdose": "Tempo Verdose",
"teod": "The End of Days",
"terra": "Terra",
"territorialio": "Territorial.io",
"territorywar": "Territory War",
"territorywar2": "Territory War 2",
"territorywar3": "Territory War 3",
"tetris": "Tetris",
"tetrisattack": "Tetris Attack",
"tetrisgba": "Tetris (GBA)",
"tetrisgrandmaster2": "Tetris Grand Master 2",
"thanksforremindingmeihadtofixthis": "Thanks for Reminding Me",
"theclassroom": "The Classroom",
"theclassroom2": "The Classroom 2",
"theclassroom3": "The Classroom 3",
"thedeadseat": "The Dead Seat",
"thedeepestsleep": "The Deepest Sleep",
"thedude": "The Dude",
"theenchantedcave2": "The Enchanted Cave 2",
"theimpossiblegame": "The Impossible Game",
"theincrediblemachine": "The Incredible Machine",
"thelaststand": "The Last Stand",
"thelaststandunioncity (1)": "The Last Stand: Union City",
"thelaststandunioncity": "The Last Stand: Union City",
"TheLoneRanger": "The Lone Ranger",
"themaninthewindow": "The Man in the Window",
"themepark": "Theme Park",
"thepit": "The Pit",
"thereisnofile": "There Is No File",
"thermomorph": "Thermomorph",
"thesodorrace": "The Sodor Race",
"TheSunForTheVampire": "The Sun for the Vampire",
"theyarecoming": "They Are Coming",
"thisistheonlylevel": "This is the Only Level",
"thisistheonlylevel2": "This is the Only Level 2",
"thisistheonlyleveltoo": "This is the Only Level Too",
"threegoblets": "Three Goblets",
"throwapotato": "Throw a Potato",
"throwapotatoagain": "Throw a Potato Again",
"thwack": "Thwack",
"tiberiandawn": "Command & Conquer: Tiberian Dawn",
"timeshooter2": "Time Shooter 2",
"timeshooter3": "Time Shooter 3",
"timewarriors": "Time Warriors",
"tinyfishing": "Tiny Fishing",
"tmnt": "TMNT",
"tmnt2arc": "TMNT 2 Arcade",
"tmntarc": "TMNT Arcade",
"tmntturtlesintime": "TMNT: Turtles in Time",
"toastarling": "Toastarling",
"toasterball": "Toaster Ball",
"toejam&earl": "ToeJam & Earl",
"toejam&earlpof": "ToeJam & Earl: Panic on Funkotron",
"tombofthemass": "Tomb of the Mass",
"tommorowandyesterday": "Tomorrow and Yesterday",
"tomodachicollection": "Tomodachi Collection",
"tonyhawkskater2": "Tony Hawk's Pro Skater 2",
"tonyhawkskater4": "Tony Hawk's Pro Skater 4",
"tonyhawksunderground": "Tony Hawk's Underground",
"toomanytypes": "Too Many Types",
"topspeedracing3d": "Top Speed Racing 3D",
"tosstheturtle": "Toss the Turtle",
"totm": "TOTM",
"touhou": "Touhou 1",
"touhou2": "Touhou 2",
"touhou3": "Touhou 3",
"touhou4": "Touhou 4",
"touhou5": "Touhou 5",
"towerblocks": "Tower Blocks",
"towercrash3d": "Tower Crash 3D",
"towerwizard": "Tower Wizard",
"townscraper": "Townscaper",
"trace": "Trace",
"trafficjam3d": "Traffic Jam 3D",
"tralalerotralalaescapetungtungtungsahur": "Tralalero Escape",
"trappedwithjester": "Trapped with Jester",
"trapthecat": "Trap the Cat",
"trechoroustrials": "Treacherous Trials",
"trechoroustrialspart2": "Treacherous Trials Part 2",
"triachnid": "Triachnid",
"tripleplay2000": "Triple Play 2000",
"triviacrack": "Trivia Crack",
"trollfacequest1": "Troll Face Quest 1",
"trollfacequest10": "Troll Face Quest 10",
"trollfacequest11": "Troll Face Quest 11",
"trollfacequest12": "Troll Face Quest 12",
"trollfacequest13": "Troll Face Quest 13",
"trollfacequest2": "Troll Face Quest 2",
"trollfacequest3": "Troll Face Quest 3",
"trollfacequest4": "Troll Face Quest 4",
"trollfacequest5": "Troll Face Quest 5",
"trollfacequest6": "Troll Face Quest 6",
"trollfacequest7": "Troll Face Quest 7",
"trollfacequest8": "Troll Face Quest 8",
"trollfacequest9": "Troll Face Quest 9",
"trucksim": "Truck Simulator",
"tsuzukimaze": "Tsuzuki Maze",
"tubejumpers": "Tube Jumpers",
"tungtunghorror": "Tung Tung Horror",
"tungtungtungsahurobby": "Tung Tung Tung Sahur Obby",
"tunnelrush": "Tunnel Rush",
"tunnelrushbetter": "Tunnel Rush (Better)",
"tupertariotros": "Tuper Tario Tros",
"turbostars": "Turbo Stars",
"turokdinosaurhunter": "Turok: Dinosaur Hunter",
"twinshot (1)": "Twin Shot",
"twinshot(1)": "Twin Shot",
"twinshot": "Twin Shot",
"twistedmetal": "Twisted Metal",
"twistedmetal2": "Twisted Metal 2",
"twoball3d": "Two Ball 3D",
"ucds": "UCDS",
"uckyblockobbyEUOPHRATESRIVER": "Lucky Block Obby",
"ufoswampoddysey": "UFO Swamp Odyssey",
"ultima": "Ultima",
"ultimateassassian2": "Ultimate Assassin 2",
"ultimateassassian3": "Ultimate Assassin 3",
"Ultimatecardrivingsimulator": "Ultimate Car Driving Simulator",
"ultimatemortalkombat": "Ultimate Mortal Kombat",
"ultimatemortalkombat3": "Ultimate Mortal Kombat 3",
"ultrakill": "Ultrakill",
"umjammerlammy": "Um Jammer Lammy",
"umstickmangameidkiforgor": "Um Stickman Game",
"uncannycatgolf": "Uncanny Cat Golf",
"underneath": "Underneath",
"undertalelb": "Undertale LB",
"undertaler": "Undertale R",
"undertaleyellow": "Undertale Yellow",
"unfairmario": "Unfair Mario",
"unfairmarioworkquestionmark": "Unfair Mario (Working)",
"unfairundyne": "Unfair Undyne",
"unicyclehero": "Unicycle Hero",
"unitresdreams": "Uni Tres Dreams",
"uno": "Uno",
"unownking": "Unown King",
"untime": "Untime",
"untitledgoosegame": "Untitled Goose Game",
"upgradecomplete": "Upgrade Complete",
"upgradecomplete2": "Upgrade Complete 2",
"upslash": "Upslash",
"usterrush": "Cluster Rush",
"UZG": "UZG",
"vampiresurvivors": "Vampire Survivors",
"vanguard": "Vanguard",
"vaportrails": "Vapor Trails",
"vex": "Vex",
"vex2": "Vex 2",
"vex3": "Vex 3",
"vex3xmas": "Vex 3 Xmas",
"vex4": "Vex 4",
"vex5": "Vex 5",
"vex6": "Vex 6",
"vex7": "Vex 7",
"vex8": "Vex 8",
"vexchallenges": "Vex Challenges",
"vexx3m": "Vexx 3M",
"vexx3m2": "Vexx 3M 2",
"villager": "Villager",
"vincentmansionofthedead": "Vincent: Mansion of the Dead",
"visitor": "The Visitor",
"volleyrandom": "Volley Random",
"vollyballchallenge": "Volleyball Challenge",
"vortex": "Vortex",
"vsagore": "VS Agore",
"vsnonsense": "VS Nonsense",
"VSSMB": "VS Super Mario Bros.",
"vvvvvv(1)": "VVVVVV",
"vvvvvv": "VVVVVV",
"waluigitacostand": "Waluigi Taco Stand",
"warfare1917": "Warfare 1917",
"warfare1944": "Warfare 1944",
"warioland1": "Wario Land",
"warioland3": "Wario Land 3",
"warioland4": "Wario Land 4",
"wariowarediy": "WarioWare D.I.Y.",
"wariowareinc": "WarioWare Inc.",
"wartheknight": "War the Knight",
"waterpoolio": "Water Pool.io",
"waterworks": "Waterworks",
"wavedash": "Wavedash",
"waverace64": "Wave Race 64",
"waverun": "Wave Run",
"webecomewhatwebehold": "We Become What We Behold",
"webfishing": "Webfishing",
"weltling": "Weltling",
"wermhole": "Wormhole",
"whackthetheif": "Whack the Thief",
"whackyourboss": "Whack Your Boss",
"whackyourcomputer": "Whack Your Computer",
"whatamarioworld": "What a Mario World",
"wheeliebike": "Wheelie Bike",
"wheely": "Wheely",
"wheely2": "Wheely 2",
"wheely3": "Wheely 3",
"wheely4": "Wheely 4",
"wheely5": "Wheely 5",
"wheely6": "Wheely 6",
"wheely7": "Wheely 7",
"wheely8": "Wheely 8",
"wilywars": "Mega Man: The Wily Wars",
"windowsdoors": "Windows Doors",
"winterfalling": "Winter Falling",
"winterolympics": "Winter Olympics",
"wipeout2097": "Wipeout 2097",
"wipeout2097alt": "Wipeout 2097 (Alt)",
"witchcrafttd": "Witchcraft TD",
"wolfchild": "Wolf Child",
"wolfenstein": "Wolfenstein",
"wolfenstein3d": "Wolfenstein 3D",
"woodworm": "Woodworm",
"wordle": "Wordle",
"worldcup98": "World Cup '98",
"worldshardestgame": "The World's Hardest Game",
"worldshardestgame2": "The World's Hardest Game 2",
"worldshardestgame3": "The World's Hardest Game 3",
"worldshardestgame4": "The World's Hardest Game 4",
"wpnfire": "Weapon Fire",
"wrassling": "Wrassling",
"wrestlebros": "Wrestle Bros",
"wwfattitude": "WWF Attitude",
"wwfsmackdown2": "WWF SmackDown! 2",
"xevent": "X Event",
"Xevious": "Xevious",
"xmenarcade": "X-Men Arcade",
"XMenChildrenOfTheAtomArcade": "X-Men: Children of the Atom Arcade",
"XMenVSStreetFighter": "X-Men vs. Street Fighter",
"yanderesimulator": "Yandere Simulator",
"yarsrevenge": "Yars' Revenge",
"yellow": "Yellow",
"yohohoio": "YoHoHo.io",
"YoshisStrangeQuest": "Yoshi's Strange Quest",
"youarelucky": "You Are Lucky",
"yourturntodie": "Your Turn to Die",
"youvs100skibidi": "You vs. 100 Skibidi",
"yumenikki": "Yume Nikki",
"zdoom": "ZDoom",
"zelda2thelegendoflink": "Zelda II: The Adventure of Link",
"ZeldaIndigoch2": "Zelda Indigo Chapter 2",
"zeldaminishcap": "Zelda: The Minish Cap",
"zenword": "Zen Word",
"zoinkz": "Zoinkz",
"zombieexploder": "Zombie Exploder",
"zombieroad": "Zombie Road",
"zombierush": "Zombie Rush",
"zombiesatemyneighboors": "Zombies Ate My Neighbors",
"zombopaclypse2": "Zombopocalypse 2",
"zombotron": "Zombotron",
"zombotron2": "Zombotron 2",
"zombotronreboot": "Zombotron Reboot",
"zrist": "Zrist",
"zuma": "Zuma",
"zumashooter": "Zuma Shooter"
};
    // Build reverse map: pretty name -> original key
    window._ugsReverseNameMap = {};
    for (var _k in window._ugsNameMap) {
        window._ugsReverseNameMap[window._ugsNameMap[_k]] = _k;
    }
    </script>
